// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003 (Category DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// CreateCategoryReq defines the input required to create a new category.
// @Description Category creation request payload.
type CreateCategoryReq struct {
	// Category name (unique, 3-255 characters)
	// @example Beverages
	Name string `json:"name" binding:"required,min=3,max=255" example:"Beverages"`

	// Category description (up to 255 characters)
	// @example Soft drinks, juices, water, and energy drinks
	Description string `json:"description" binding:"required,max=255" example:"Soft drinks, juices, water, and energy drinks"`
}

// UpdateCategoryReq defines the input required to update an existing category.
// @Description Category update request payload.
type UpdateCategoryReq struct {
	// Category updated name (3-255 characters)
	// @example Carbonated Beverages
	Name string `json:"name" binding:"required,min=3,max=255" example:"Carbonated Beverages"`

	// Category updated description (up to 255 characters)
	// @example All carbonated and non-carbonated soft drinks
	Description string `json:"description" binding:"required,max=255" example:"All carbonated and non-carbonated soft drinks"`
}

// CategoryResponse represents the output structure for a category.
// @Description Category response payload.
type CategoryResponse struct {
	// Unique identifier for the category
	// @example 1
	ID uint64 `json:"id" example:"1"`

	// Category name
	// @example Beverages
	Name string `json:"name" example:"Beverages"`

	// Category description
	// @example Soft drinks, juices, water, and energy drinks
	Description string `json:"description" example:"Soft drinks, juices, water, and energy drinks"`

	// Timestamp when the category was created
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}
