// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003 (Client DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// CreateClientReq defines the input required to register a client in the system.
// @Description Client registration request payload.
type CreateClientReq struct {
	// Client's full name (3-255 characters)
	// @example Jane Doe
	Name string `json:"name" binding:"required,min=3,max=255" example:"Jane Doe"`

	// Client's unique National ID (DNI) (Must be exactly 10 numeric digits)
	// @example 1712345678
	DNI string `json:"dni" binding:"required,numeric,len=10" example:"1712345678"`

	// Client's email address
	// @example jane.doe@example.com
	Email string `json:"email" binding:"required,email" example:"jane.doe@example.com"`
}

// UpdateClientReq defines the input required to update client details.
// @Description Client profile update request payload.
type UpdateClientReq struct {
	// Client's updated full name (3-255 characters)
	// @example Jane Smith
	Name string `json:"name" binding:"required,min=3,max=255" example:"Jane Smith"`

	// Client's updated National ID (DNI) (Must be exactly 10 numeric digits)
	// @example 1712345678
	DNI string `json:"dni" binding:"required,numeric,len=10" example:"1712345678"`

	// Client's updated email address
	// @example jane.smith@example.com
	Email string `json:"email" binding:"required,email" example:"jane.smith@example.com"`
}

// ClientResponse represents the output structure for client profiles.
// @Description Client profile response payload.
type ClientResponse struct {
	// Unique identifier for the client
	// @example 5
	ID uint64 `json:"id" example:"5"`

	// Client's full name
	// @example Jane Doe
	Name string `json:"name" example:"Jane Doe"`

	// Client's National ID (DNI)
	// @example 1712345678
	DNI string `json:"dni" example:"1712345678"`

	// Client's email address
	// @example jane.doe@example.com
	Email string `json:"email" example:"jane.doe@example.com"`

	// Timestamp when the client profile was created
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}