// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003 (Common DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// SimpleMsg represents a generic message response.
// @Description Simple message response payload.
type SimpleMsg struct {
	// The message body
	// @example Operation successful
	Message string `json:"message" example:"Operation successful"`
}

// ErrorResponse represents an error response payload.
// @Description Error details returned when an operation fails.
type ErrorResponse struct {
	// The business/application error code
	// @example NOT_FOUND
	ErrorCode string `json:"errorCode" example:"NOT_FOUND"`

	// Detailed error message
	// @example Resource not found
	Message string `json:"message" example:"Resource not found"`

	// Time of the error occurrence
	// @example 2025-02-14T17:00:00Z
	Timestamp time.Time `json:"timestamp" example:"2025-02-14T17:00:00Z"`
}