// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003 (Product DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// CreateProductReq defines the input required to create a new product.
// @Description Product creation request payload.
type CreateProductReq struct {
	// Product name (3-255 characters)
	// @example Coca Cola 1.5L
	Name string `json:"name" binding:"required,min=3,max=255" example:"Coca Cola 1.5L"`

	// Product brand name
	// @example Coca Cola
	Brand string `json:"brand" binding:"required,max=255" example:"Coca Cola"`

	// Product base price before taxes (must be greater than 0)
	// @example 1.85
	BasePrice float64 `json:"basePrice" binding:"required,gt=0" example:"1.85"`

	// Product value added tax percentage (must be greater than or equal to 0)
	// @example 12.0
	TaxPercentage float64 `json:"taxPercentage" binding:"required,gte=0" example:"12.0"`

	// Associated Category ID
	// @example 1
	CategoryID uint64 `json:"categoryId" binding:"required" example:"1"`

	// Initial stock inventory level (must be greater than or equal to 0)
	// @example 100
	Stock int `json:"stock" binding:"required,gte=0" example:"100"`
}

// UpdateProductReq defines the input required to update an existing product.
// @Description Product update request payload.
type UpdateProductReq struct {
	// Product updated name (3-255 characters)
	// @example Coca Cola Zero 1.5L
	Name string `json:"name" binding:"required,min=3,max=255" example:"Coca Cola Zero 1.5L"`

	// Product updated brand name
	// @example Coca Cola
	Brand string `json:"brand" binding:"required,max=255" example:"Coca Cola"`

	// Product updated base price before taxes (must be greater than 0)
	// @example 1.95
	BasePrice float64 `json:"basePrice" binding:"required,gt=0" example:"1.95"`

	// Product updated value added tax percentage (must be greater than or equal to 0)
	// @example 12.0
	TaxPercentage float64 `json:"taxPercentage" binding:"required,gte=0" example:"12.0"`

	// Updated Associated Category ID
	// @example 1
	CategoryID uint64 `json:"categoryId" binding:"required" example:"1"`

	// Updated stock inventory level (must be greater than or equal to 0)
	// @example 150
	Stock int `json:"stock" binding:"required,gte=0" example:"150"`
}

// ProductResponse represents the output structure for a product.
// @Description Product response payload.
type ProductResponse struct {
	// Unique identifier for the product
	// @example 42
	ID uint64 `json:"id" example:"42"`

	// Product name
	// @example Coca Cola 1.5L
	Name string `json:"name" example:"Coca Cola 1.5L"`

	// Product brand
	// @example Coca Cola
	Brand string `json:"brand" example:"Coca Cola"`

	// Product base price before taxes
	// @example 1.85
	BasePrice float64 `json:"basePrice" example:"1.85"`

	// Value added tax percentage
	// @example 12.0
	TaxPercentage float64 `json:"taxPercentage" example:"12.0"`

	// Associated Category ID
	// @example 1
	CategoryID uint64 `json:"categoryId" example:"1"`

	// Current available stock
	// @example 100
	Stock int `json:"stock" example:"100"`

	// Timestamp when the product was registered
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}

// RestockReq defines the input required to add stock to a product.
// @Description Restock inventory request payload.
type RestockReq struct {
	// Quantity of units to add (must be greater than 0)
	// @example 50
	Quantity int `json:"quantity" binding:"required,gt=0" example:"50"`
}

// PriceBreakdownResponse represents the breakdown of taxes and promotion discounts.
// @Description Price breakdown response including promotional discounts and final prices.
type PriceBreakdownResponse struct {
	// Unique identifier for the product
	// @example 42
	ProductID uint64 `json:"productId" example:"42"`

	// Product base price before tax
	// @example 1.85
	BasePrice float64 `json:"basePrice" example:"1.85"`

	// Final price with tax but without promotion discount
	// @example 2.07
	StandardFinalPrice float64 `json:"standardFinalPrice" example:"2.07"`

	// Promotion details applied, if active
	AppliedPromotion *PromoShortResponse `json:"appliedPromotion,omitempty"`

	// Final price with tax and promotional discount applied
	// @example 1.86
	PromotionalFinalPrice float64 `json:"promotionalFinalPrice" example:"1.86"`
}

// PromoShortResponse represents a high-level promo summary for price breakdown.
// @Description Short promotion summary information.
type PromoShortResponse struct {
	// Unique identifier for the promotion
	// @example 7
	ID uint64 `json:"id" example:"7"`

	// Promotion campaign name
	// @example Weekend Discount
	Name string `json:"name" example:"Weekend Discount"`

	// Active discount percentage (e.g. 10.0 for 10% off)
	// @example 10.0
	DiscountPercentage float64 `json:"discountPercentage" example:"10.0"`
}