// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003 (Promotion DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// CreatePromotionReq defines the input required to create a new promotion.
// @Description Promotion creation request payload.
type CreatePromotionReq struct {
	// Name of the promotion campaign (3-255 characters)
	// @example Black Friday Sale
	Name string `json:"name" binding:"required,min=3,max=255" example:"Black Friday Sale"`

	// Discount percentage to apply (must be > 0 and <= 100)
	// @example 15.0
	DiscountPercentage float64 `json:"discountPercentage" binding:"required,gt=0,lte=100" example:"15.0"`

	// Promotion start date and time
	// @example 2025-02-14T00:00:00Z
	StartDate time.Time `json:"startDate" binding:"required" example:"2025-02-14T00:00:00Z"`

	// Promotion end date and time
	// @example 2025-02-16T23:59:59Z
	EndDate time.Time `json:"endDate" binding:"required" example:"2025-02-16T23:59:59Z"`

	// IDs of products included in the promotion campaign (at least one)
	// @example [1, 2, 42]
	ProductIDs []uint64 `json:"productIds" binding:"required,min=1" example:"1,2,42"`
}

// UpdatePromotionReq defines the input required to update an existing promotion.
// @Description Promotion update request payload.
type UpdatePromotionReq struct {
	// Updated name of the promotion campaign (3-255 characters)
	// @example Super Saturday Sale
	Name string `json:"name" binding:"required,min=3,max=255" example:"Super Saturday Sale"`

	// Updated discount percentage to apply (must be > 0 and <= 100)
	// @example 20.0
	DiscountPercentage float64 `json:"discountPercentage" binding:"required,gt=0,lte=100" example:"20.0"`

	// Updated promotion start date and time
	// @example 2025-02-15T00:00:00Z
	StartDate time.Time `json:"startDate" binding:"required" example:"2025-02-15T00:00:00Z"`

	// Updated promotion end date and time
	// @example 2025-02-15T23:59:59Z
	EndDate time.Time `json:"endDate" binding:"required" example:"2025-02-15T23:59:59Z"`
}

// PromotionResponse represents the output structure for a promotion campaign.
// @Description Promotion response payload.
type PromotionResponse struct {
	// Unique identifier for the promotion
	// @example 7
	ID uint64 `json:"id" example:"7"`

	// Name of the promotion campaign
	// @example Black Friday Sale
	Name string `json:"name" example:"Black Friday Sale"`

	// Active discount percentage
	// @example 15.0
	DiscountPercentage float64 `json:"discountPercentage" example:"15.0"`

	// Promotion start date and time
	// @example 2025-02-14T00:00:00Z
	StartDate time.Time `json:"startDate" example:"2025-02-14T00:00:00Z"`

	// Promotion end date and time
	// @example 2025-02-16T23:59:59Z
	EndDate time.Time `json:"endDate" example:"2025-02-16T23:59:59Z"`

	// Timestamp when the promotion was created
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}

// LinkProductsReq defines the input to link multiple products to a promotion.
// @Description Request payload to link products to a promotion.
type LinkProductsReq struct {
	// IDs of products to associate with the promotion (at least one)
	// @example [3, 4, 5]
	ProductIDs []uint64 `json:"productIds" binding:"required,min=1" example:"3,4,5"`
}
