// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003, CTR-002 (Sales & Pagination DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// OpenSaleRequest defines the input to open a new active sale transaction.
// @Description Request payload to open a new sale.
type OpenSaleRequest struct {
	// Optional associated client ID for registered client benefits
	// @example 5
	ClientID *uint64 `json:"clientId" example:"5"`
}

// AddItemRequest defines the input required to add a product line item to a sale.
// @Description Request payload to add a product to an open sale.
type AddItemRequest struct {
	// Unique identifier for the product
	// @example 42
	ProductID uint64 `json:"productId" binding:"required" example:"42"`

	// Quantity of units to add (must be greater than 0)
	// @example 3
	Quantity int `json:"quantity" binding:"required,gt=0" example:"3"`
}

// UpdateItemQtyRequest defines the input to modify an existing item's quantity in a sale.
// @Description Request payload to update an item's quantity in a sale.
type UpdateItemQtyRequest struct {
	// Updated quantity of units (must be greater than 0)
	// @example 5
	Quantity int `json:"quantity" binding:"required,gt=0" example:"5"`
}

// SaleResponse represents the general high-level status of a sale.
// @Description Sale status response payload.
type SaleResponse struct {
	// Unique identifier for the sale transaction
	// @example 101
	ID uint64 `json:"id" example:"101"`

	// Total accumulated price of the sale including taxes and promotion discounts
	// @example 12.45
	TotalPrice float64 `json:"totalPrice" example:"12.45"`

	// Current state of the transaction (e.g., ACTIVE, FINALIZED, CANCELLED)
	// @example ACTIVE
	Status string `json:"status" example:"ACTIVE"`

	// ID of the client associated with the sale (null if unregistered/guest)
	// @example 5
	ClientID *uint64 `json:"clientId,omitempty" example:"5"`

	// ID of the cashier/operator executing the sale
	// @example 1
	CashierID uint64 `json:"cashierId" example:"1"`

	// Timestamp when the transaction was completed (null if still active)
	// @example 2025-02-14T17:30:00Z
	FinishedAt *time.Time `json:"finishedAt,omitempty" example:"2025-02-14T17:30:00Z"`

	// Timestamp when the transaction was initiated
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}

// SaleDetailResponse represents a detailed sale including its itemized breakdown.
// @Description Complete sale details including line items.
type SaleDetailResponse struct {
	// General status of the sale transaction
	Sale SaleResponse `json:"sale"`

	// Itemized product lines in the transaction
	LineItems []LineItemResponse `json:"lineItems"`
}

// LineItemResponse represents a single product line detail in a sale transaction.
// @Description Detail of an itemized line inside a sale.
type LineItemResponse struct {
	// Unique identifier for the line item inside this sale
	// @example 201
	ItemID uint64 `json:"itemId" example:"201"`

	// Unique identifier of the product sold
	// @example 42
	ProductID uint64 `json:"productId" example:"42"`

	// Product name at the time of sale
	// @example Coca Cola 1.5L
	Name string `json:"productName" example:"Coca Cola 1.5L"`

	// Computed unit price (tax-inclusive and discount-inclusive) at the time of purchase
	// @example 1.86
	UnitPrice float64 `json:"unitPrice" example:"1.86"`

	// Number of units purchased
	// @example 3
	Quantity int `json:"quantity" example:"3"`

	// Total subtotal for this itemized line (unitPrice * quantity)
	// @example 5.58
	SubTotal float64 `json:"subTotal" example:"5.58"`
}

// PaginatedUsers represents a page of operator profiles.
// @Description Paginated list of users.
type PaginatedUsers struct {
	// Page items
	Items []UserResponse `json:"items"`

	// Total matching items in system
	// @example 50
	TotalCount int64 `json:"totalCount" example:"50"`
}

// PaginatedCategories represents a page of categories.
// @Description Paginated list of categories.
type PaginatedCategories struct {
	// Page items
	Items []CategoryResponse `json:"items"`

	// Total matching items in system
	// @example 15
	TotalCount int64 `json:"totalCount" example:"15"`
}

// PaginatedProducts represents a page of products.
// @Description Paginated list of products.
type PaginatedProducts struct {
	// Page items
	Items []ProductResponse `json:"items"`

	// Total matching items in system
	// @example 250
	TotalCount int64 `json:"totalCount" example:"250"`
}

// PaginatedClients represents a page of clients.
// @Description Paginated list of clients.
type PaginatedClients struct {
	// Page items
	Items []ClientResponse `json:"items"`

	// Total matching items in system
	// @example 120
	TotalCount int64 `json:"totalCount" example:"120"`
}

// PaginatedPromotions represents a page of promotion campaigns.
// @Description Paginated list of promotions.
type PaginatedPromotions struct {
	// Page items
	Items []PromotionResponse `json:"items"`

	// Total matching items in system
	// @example 8
	TotalCount int64 `json:"totalCount" example:"8"`
}

// PaginatedSales represents a page of sales transactions.
// @Description Paginated list of sales.
type PaginatedSales struct {
	// Page items
	Items []SaleResponse `json:"items"`

	// Total matching items in system
	// @example 3200
	TotalCount int64 `json:"totalCount" example:"3200"`
}