// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003, CTR-001 (User / Auth DTOs)
// Service: SupermarketService
// Target Concern: dtos

package dto

import "time"

// RegisterRequest defines the input required to register a new operator/user.
// @Description Registration request payload.
type RegisterRequest struct {
	// Operator's full name
	// @example John Doe
	FullName string `json:"fullName" binding:"required,min=3,max=255" example:"John Doe"`

	// Operator's unique login username
	// @example johndoe123
	Username string `json:"username" binding:"required,alphanum,min=3,max=50" example:"johndoe123"`

	// Operator's secure account password
	// @example SecretP@ss123
	Password string `json:"password" binding:"required,min=8,max=100" example:"SecretP@ss123"`

	// Operator's role (must be ADMIN, CASHIER, or INVENTORY)
	// @example CASHIER
	Role string `json:"role" binding:"required,oneof=ADMIN CASHIER INVENTORY" example:"CASHIER"`
}

// LoginRequest defines the credentials required to log in.
// @Description Authentication credentials request payload.
type LoginRequest struct {
	// Operator's username
	// @example johndoe123
	Username string `json:"username" binding:"required" example:"johndoe123"`

	// Operator's password
	// @example SecretP@ss123
	Password string `json:"password" binding:"required" example:"SecretP@ss123"`
}

// LoginResponse represents the output returned upon successful authentication.
// @Description Authentication success response payload.
type LoginResponse struct {
	// Issued JWT token
	// @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
	Token string `json:"token" example:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."`

	// Expiration timestamp of the issued JWT token
	// @example 2025-02-14T23:00:00Z
	ExpiresAt time.Time `json:"expiresAt" example:"2025-02-14T23:00:00Z"`

	// Operator profile information
	User UserResponse `json:"user"`
}

// UserResponse represents the public operator profile.
// @Description Operator account response profile.
type UserResponse struct {
	// Unique identifier for the operator
	// @example 1
	ID uint64 `json:"id" example:"1"`

	// Operator's full name
	// @example John Doe
	FullName string `json:"fullName" example:"John Doe"`

	// Operator's unique username
	// @example johndoe123
	Username string `json:"username" example:"johndoe123"`

	// Operator's role (ADMIN, CASHIER, or INVENTORY)
	// @example CASHIER
	Role string `json:"role" example:"CASHIER"`

	// Timestamp when the operator account was created
	// @example 2025-02-14T17:00:00Z
	CreatedAt time.Time `json:"createdAt" example:"2025-02-14T17:00:00Z"`
}

// UpdateUserRequest defines the fields that can be updated for an operator's account.
// @Description Profile update request payload. All fields are optional.
type UpdateUserRequest struct {
	// Operator's updated full name (optional)
	// @example John Updated Doe
	FullName string `json:"fullName" binding:"omitempty,min=3,max=255" example:"John Updated Doe"`

	// Operator's new secure password (optional)
	// @example NewSecretP@ss123
	Password string `json:"password" binding:"omitempty,min=8,max=100" example:"NewSecretP@ss123"`
}