// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-002, CTR-005 (Category Database Operations)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"supermarket-backend/entities"
)

// CategoryRepository defines database operations for Category entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-73-category-creation-with-unique-check-fr-005
type CategoryRepository interface {
	Create(ctx context.Context, category *entities.Category) error
	FindByID(ctx context.Context, id uint64) (*entities.Category, error)
	FindByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Category, error)
	Update(ctx context.Context, category *entities.Category) error
	Delete(ctx context.Context, id uint64) error
	FindAll(ctx context.Context, offset, limit int) ([]entities.Category, int64, error)
	ExistsByNameCaseInsensitive(ctx context.Context, name string) (bool, error)
	SoftDeleteWithTx(ctx context.Context, tx *gorm.DB, id uint64) error
}

type categoryRepository struct {
	db *gorm.DB
}

// NewCategoryRepository creates a new CategoryRepository instance.
func NewCategoryRepository(db *gorm.DB) CategoryRepository {
	return &categoryRepository{db: db}
}

// Create inserts a new category record.
func (r *categoryRepository) Create(ctx context.Context, category *entities.Category) error {
	return r.db.WithContext(ctx).Create(category).Error
}

// FindByID retrieves a category by its unique primary key.
func (r *categoryRepository) FindByID(ctx context.Context, id uint64) (*entities.Category, error) {
	var category entities.Category
	err := r.db.WithContext(ctx).First(&category, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &category, nil
}

// FindByIDWithLock retrieves a category with pessimistic lock (SELECT FOR UPDATE).
func (r *categoryRepository) FindByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Category, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var category entities.Category
	err := db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).First(&category, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &category, nil
}

// Update updates an existing category record.
func (r *categoryRepository) Update(ctx context.Context, category *entities.Category) error {
	return r.db.WithContext(ctx).Save(category).Error
}

// Delete soft-deletes a category record.
func (r *categoryRepository) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entities.Category{}, id).Error
}

// FindAll lists categories with offset pagination and returns the total count.
func (r *categoryRepository) FindAll(ctx context.Context, offset, limit int) ([]entities.Category, int64, error) {
	var categories []entities.Category
	var total int64

	err := r.db.WithContext(ctx).Model(&entities.Category{}).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = r.db.WithContext(ctx).Offset(offset).Limit(limit).Find(&categories).Error
	if err != nil {
		return nil, 0, err
	}

	return categories, total, nil
}

// ExistsByNameCaseInsensitive performs a case-insensitive check for active category names.
// Index used: idx_category_active (name, deleted_at)
func (r *categoryRepository) ExistsByNameCaseInsensitive(ctx context.Context, name string) (bool, error) {
	var count int64
	// Lowercase conversion is safe and standard in database query
	err := r.db.WithContext(ctx).Model(&entities.Category{}).
		Where("LOWER(name) = ?", strings.ToLower(name)).
		Count(&count).Error
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// SoftDeleteWithTx soft-deletes a category using an existing GORM transaction.
func (r *categoryRepository) SoftDeleteWithTx(ctx context.Context, tx *gorm.DB, id uint64) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Delete(&entities.Category{}, id).Error
}