// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-003, CTR-005 (Client Database Operations)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"
	"strings"

	"gorm.io/gorm"
	"supermarket-backend/entities"
)

// ClientRepository defines the database operations for Client entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-3-complete-api-table-all-37-endpoints
type ClientRepository interface {
	Create(ctx context.Context, client *entities.Client) error
	FindByID(ctx context.Context, id uint64) (*entities.Client, error)
	Update(ctx context.Context, client *entities.Client) error
	Delete(ctx context.Context, id uint64) error
	FindAll(ctx context.Context, offset, limit int) ([]entities.Client, int64, error)
	FindByDNI(ctx context.Context, dni string) (*entities.Client, error)
	FindByEmail(ctx context.Context, email string) (*entities.Client, error)
	Search(ctx context.Context, query string) ([]entities.Client, error)
}

type clientRepository struct {
	db *gorm.DB
}

// NewClientRepository creates a new ClientRepository instance.
func NewClientRepository(db *gorm.DB) ClientRepository {
	return &clientRepository{db: db}
}

// Create inserts a new client record.
func (r *clientRepository) Create(ctx context.Context, client *entities.Client) error {
	return r.db.WithContext(ctx).Create(client).Error
}

// FindByID retrieves a client by its unique primary key.
func (r *clientRepository) FindByID(ctx context.Context, id uint64) (*entities.Client, error) {
	var client entities.Client
	err := r.db.WithContext(ctx).First(&client, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &client, nil
}

// Update updates an existing client record.
func (r *clientRepository) Update(ctx context.Context, client *entities.Client) error {
	return r.db.WithContext(ctx).Save(client).Error
}

// Delete soft-deletes a client record.
func (r *clientRepository) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entities.Client{}, id).Error
}

// FindAll lists clients with offset pagination and returns the total count.
func (r *clientRepository) FindAll(ctx context.Context, offset, limit int) ([]entities.Client, int64, error) {
	var clients []entities.Client
	var total int64

	err := r.db.WithContext(ctx).Model(&entities.Client{}).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = r.db.WithContext(ctx).Offset(offset).Limit(limit).Find(&clients).Error
	if err != nil {
		return nil, 0, err
	}

	return clients, total, nil
}

// FindByDNI retrieves a client by their unique DNI.
// Index used: idx_client_dni_active (dni, deleted_at)
func (r *clientRepository) FindByDNI(ctx context.Context, dni string) (*entities.Client, error) {
	var client entities.Client
	err := r.db.WithContext(ctx).Where("dni = ?", dni).First(&client).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &client, nil
}

// FindByEmail retrieves a client by their unique email.
// Index used: idx_client_email_active (email, deleted_at)
func (r *clientRepository) FindByEmail(ctx context.Context, email string) (*entities.Client, error) {
	var client entities.Client
	err := r.db.WithContext(ctx).Where("email = ?", email).First(&client).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &client, nil
}

// Search searches for clients matching name, dni, or email.
func (r *clientRepository) Search(ctx context.Context, query string) ([]entities.Client, error) {
	var clients []entities.Client
	q := "%" + strings.ToLower(query) + "%"

	err := r.db.WithContext(ctx).
		Where("dni = ? OR LOWER(name) LIKE ? OR LOWER(email) LIKE ?", query, q, q).
		Find(&clients).Error
	if err != nil {
		return nil, err
	}
	return clients, nil
}