// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-004 (Product Repository)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"supermarket-backend/entities"
)

// ProductRepository defines the database operations for Product entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram
// Contract ID Traceability: CTR-004
type ProductRepository interface {
	Create(ctx context.Context, product *entities.Product) error
	FindByID(ctx context.Context, id uint64) (*entities.Product, error)
	FindByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Product, error)
	Update(ctx context.Context, product *entities.Product) error
	UpdateStockWithTx(ctx context.Context, tx *gorm.DB, id uint64, stock int) error
	SoftDeleteByCategoryIDWithTx(ctx context.Context, tx *gorm.DB, categoryID uint64) error
	FindActivePromotionsByProductID(ctx context.Context, tx *gorm.DB, id uint64, t time.Time) ([]entities.Promotion, error)
	FindAll(ctx context.Context, offset, limit int) ([]entities.Product, int64, error)
	FindAllByCategoryID(ctx context.Context, categoryID uint64, offset, limit int) ([]entities.Product, int64, error)
}

type productRepository struct {
	db *gorm.DB
}

// NewProductRepository creates a new ProductRepository instance.
func NewProductRepository(db *gorm.DB) ProductRepository {
	return &productRepository{db: db}
}

// Create inserts a new product record.
func (r *productRepository) Create(ctx context.Context, product *entities.Product) error {
	return r.db.WithContext(ctx).Create(product).Error
}

// FindByID retrieves a product by its unique primary key.
func (r *productRepository) FindByID(ctx context.Context, id uint64) (*entities.Product, error) {
	var product entities.Product
	err := r.db.WithContext(ctx).First(&product, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &product, nil
}

// FindByIDWithLock retrieves a product with a pessimistic lock (SELECT FOR UPDATE).
func (r *productRepository) FindByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Product, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var product entities.Product
	err := db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).First(&product, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &product, nil
}

// Update updates an existing product record.
func (r *productRepository) Update(ctx context.Context, product *entities.Product) error {
	return r.db.WithContext(ctx).Save(product).Error
}

// UpdateStockWithTx updates the stock level of a product inside a transactional scope.
func (r *productRepository) UpdateStockWithTx(ctx context.Context, tx *gorm.DB, id uint64, stock int) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Model(&entities.Product{}).Where("id = ?", id).Update("stock", stock).Error
}

// SoftDeleteByCategoryIDWithTx performs a cascading soft-delete on all products belonging to a category inside a transaction.
// Index used: idx_product_category_id
func (r *productRepository) SoftDeleteByCategoryIDWithTx(ctx context.Context, tx *gorm.DB, categoryID uint64) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Where("category_id = ?", categoryID).Delete(&entities.Product{}).Error
}

// FindActivePromotionsByProductID queries all overlapping date-bounded promotional campaigns for a product.
// Standard GORM model relation join to ensure high performance and correct index utilization.
func (r *productRepository) FindActivePromotionsByProductID(ctx context.Context, tx *gorm.DB, id uint64, t time.Time) ([]entities.Promotion, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var promotions []entities.Promotion
	err := db.WithContext(ctx).
		Model(&entities.Promotion{}).
		Joins("JOIN promotion_products ON promotion_products.promotion_id = promotion.id").
		Where("promotion_products.product_id = ? AND promotion.start_date <= ? AND promotion.end_date >= ?", id, t, t).
		Find(&promotions).Error
	if err != nil {
		return nil, err
	}
	return promotions, nil
}

// FindAll lists products with offset pagination and returns the total count.
func (r *productRepository) FindAll(ctx context.Context, offset, limit int) ([]entities.Product, int64, error) {
	var products []entities.Product
	var total int64

	err := r.db.WithContext(ctx).Model(&entities.Product{}).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = r.db.WithContext(ctx).Offset(offset).Limit(limit).Find(&products).Error
	if err != nil {
		return nil, 0, err
	}

	return products, total, nil
}

// FindAllByCategoryID lists active products for a category with offset pagination.
func (r *productRepository) FindAllByCategoryID(ctx context.Context, categoryID uint64, offset, limit int) ([]entities.Product, int64, error) {
	var products []entities.Product
	var total int64

	err := r.db.WithContext(ctx).Model(&entities.Product{}).Where("category_id = ?", categoryID).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = r.db.WithContext(ctx).Where("category_id = ?", categoryID).Offset(offset).Limit(limit).Find(&products).Error
	if err != nil {
		return nil, 0, err
	}

	return products, total, nil
}