// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-005 (Promotion Database Operations)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"

	"gorm.io/gorm"
	"supermarket-backend/entities"
)

// PromotionRepository defines the database operations for Promotion entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-21-entity-table-schemas
type PromotionRepository interface {
	Create(ctx context.Context, promotion *entities.Promotion) error
	FindByID(ctx context.Context, id uint64) (*entities.Promotion, error)
	Update(ctx context.Context, promotion *entities.Promotion) error
	Delete(ctx context.Context, id uint64) error
	FindAll(ctx context.Context, offset, limit int) ([]entities.Promotion, int64, error)
	LinkProductsWithTx(ctx context.Context, tx *gorm.DB, promotionID uint64, productIDs []uint64) error
	UnlinkProductWithTx(ctx context.Context, tx *gorm.DB, promotionID uint64, productID uint64) error
}

type promotionRepository struct {
	db *gorm.DB
}

// NewPromotionRepository creates a new PromotionRepository instance.
func NewPromotionRepository(db *gorm.DB) PromotionRepository {
	return &promotionRepository{db: db}
}

// Create inserts a new promotion record.
func (r *promotionRepository) Create(ctx context.Context, promotion *entities.Promotion) error {
	return r.db.WithContext(ctx).Create(promotion).Error
}

// FindByID retrieves a promotion by its unique primary key and preloads linked products.
func (r *promotionRepository) FindByID(ctx context.Context, id uint64) (*entities.Promotion, error) {
	var promotion entities.Promotion
	err := r.db.WithContext(ctx).Preload("Products").First(&promotion, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &promotion, nil
}

// Update updates an existing promotion record.
func (r *promotionRepository) Update(ctx context.Context, promotion *entities.Promotion) error {
	return r.db.WithContext(ctx).Save(promotion).Error
}

// Delete soft-deletes a promotion record.
func (r *promotionRepository) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entities.Promotion{}, id).Error
}

// FindAll lists promotions with offset pagination and returns the total count.
func (r *promotionRepository) FindAll(ctx context.Context, offset, limit int) ([]entities.Promotion, int64, error) {
	var promotions []entities.Promotion
	var total int64

	err := r.db.WithContext(ctx).Model(&entities.Promotion{}).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = r.db.WithContext(ctx).Offset(offset).Limit(limit).Find(&promotions).Error
	if err != nil {
		return nil, 0, err
	}

	return promotions, total, nil
}

// LinkProductsWithTx inserts rows into the many-to-many junction table 'promotion_products'.
// Leverages MySQL INSERT IGNORE to be idempotent and ignore duplicate association errors.
func (r *promotionRepository) LinkProductsWithTx(ctx context.Context, tx *gorm.DB, promotionID uint64, productIDs []uint64) error {
	db := r.db
	if tx != nil {
		db = tx
	}

	for _, productID := range productIDs {
		err := db.WithContext(ctx).
			Exec("INSERT IGNORE INTO promotion_products (promotion_id, product_id) VALUES (?, ?)", promotionID, productID).
			Error
		if err != nil {
			return err
		}
	}
	return nil
}

// UnlinkProductWithTx removes a row from the junction table 'promotion_products'.
func (r *promotionRepository) UnlinkProductWithTx(ctx context.Context, tx *gorm.DB, promotionID uint64, productID uint64) error {
	db := r.db
	if tx != nil {
		db = tx
	}

	return db.WithContext(ctx).
		Table("promotion_products").
		Where("promotion_id = ? AND product_id = ?", promotionID, productID).
		Delete(nil).Error
}
