// Code generated by FEP sub-agent. DO NOT EDIT.
// This file is kept for package structure purposes only.
// Interfaces and implementations are now declared in their respective dedicated files.

package repositories