// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-002, CTR-005 (Sale / POS Database Operations)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"supermarket-backend/entities"
)

// SaleRepository defines the database operations for Sale and SaleDetail entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram
type SaleRepository interface {
	CreateSale(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error
	FindSaleByID(ctx context.Context, id uint64) (*entities.Sale, error)
	FindSaleByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Sale, error)
	UpdateSale(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error
	UpdateSaleWithTx(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error
	FindSales(ctx context.Context, offset, limit int, status string, clientID *uint64, cashierID *uint64) ([]entities.Sale, int64, error)
	CreateDetail(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error
	CreateDetailWithTx(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error
	FindDetailByID(ctx context.Context, id uint64) (*entities.SaleDetail, error)
	UpdateDetail(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error
	UpdateDetailWithTx(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error
	DeleteDetail(ctx context.Context, tx *gorm.DB, id uint64) error
	FindDetailBySaleAndProductWithTx(ctx context.Context, tx *gorm.DB, saleID uint64, productID uint64) (*entities.SaleDetail, error)
	FindAllDetailsBySaleIDWithTx(ctx context.Context, tx *gorm.DB, saleID uint64) ([]entities.SaleDetail, error)
}

type saleRepository struct {
	db *gorm.DB
}

// NewSaleRepository creates a new SaleRepository instance.
func NewSaleRepository(db *gorm.DB) SaleRepository {
	return &saleRepository{db: db}
}

// CreateSale inserts a new sale record. Supports running within a transactional scope.
func (r *saleRepository) CreateSale(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Create(sale).Error
}

// FindSaleByID retrieves a sale with preloaded details and line item products.
func (r *saleRepository) FindSaleByID(ctx context.Context, id uint64) (*entities.Sale, error) {
	var sale entities.Sale
	err := r.db.WithContext(ctx).
		Preload("Details").
		Preload("Details.Product").
		First(&sale, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &sale, nil
}

// FindSaleByIDWithLock retrieves a sale inside a transaction with a pessimistic write-lock (SELECT ... FOR UPDATE).
func (r *saleRepository) FindSaleByIDWithLock(ctx context.Context, tx *gorm.DB, id uint64) (*entities.Sale, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var sale entities.Sale
	err := db.WithContext(ctx).
		Clauses(clause.Locking{Strength: "UPDATE"}).
		Preload("Details").
		Preload("Details.Product").
		First(&sale, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &sale, nil
}

// UpdateSale updates an existing sale record. Supports optional transaction context.
func (r *saleRepository) UpdateSale(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Save(sale).Error
}

// UpdateSaleWithTx is an alias for UpdateSale to fully conform to varied LLD pseudocode calls.
func (r *saleRepository) UpdateSaleWithTx(ctx context.Context, tx *gorm.DB, sale *entities.Sale) error {
	return r.UpdateSale(ctx, tx, sale)
}

// FindSales lists sales with pagination, optionally filtered by status, client, and cashier.
func (r *saleRepository) FindSales(ctx context.Context, offset, limit int, status string, clientID *uint64, cashierID *uint64) ([]entities.Sale, int64, error) {
	var sales []entities.Sale
	var total int64

	query := r.db.WithContext(ctx).Model(&entities.Sale{})

	if status != "" {
		query = query.Where("status = ?", status)
	}
	if clientID != nil && *clientID != 0 {
		query = query.Where("client_id = ?", *clientID)
	}
	if cashierID != nil && *cashierID != 0 {
		query = query.Where("cashier_id = ?", *cashierID)
	}

	err := query.Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	err = query.Offset(offset).Limit(limit).Find(&sales).Error
	if err != nil {
		return nil, 0, err
	}

	return sales, total, nil
}

// CreateDetail inserts a new sale detail line item. Supports optional transaction context.
func (r *saleRepository) CreateDetail(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Create(detail).Error
}

// CreateDetailWithTx is an alias for CreateDetail to conform with LLD sequence diagrams and service layer pseudocode.
func (r *saleRepository) CreateDetailWithTx(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error {
	return r.CreateDetail(ctx, tx, detail)
}

// FindDetailByID retrieves a specific sale detail record.
func (r *saleRepository) FindDetailByID(ctx context.Context, id uint64) (*entities.SaleDetail, error) {
	var detail entities.SaleDetail
	err := r.db.WithContext(ctx).Preload("Product").First(&detail, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &detail, nil
}

// UpdateDetail updates an existing sale detail line item. Supports optional transaction context.
func (r *saleRepository) UpdateDetail(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Save(detail).Error
}

// UpdateDetailWithTx is an alias for UpdateDetail to satisfy varied call styles in LLD.
func (r *saleRepository) UpdateDetailWithTx(ctx context.Context, tx *gorm.DB, detail *entities.SaleDetail) error {
	return r.UpdateDetail(ctx, tx, detail)
}

// DeleteDetail removes a sale detail line item (hard-delete inside transaction scope).
func (r *saleRepository) DeleteDetail(ctx context.Context, tx *gorm.DB, id uint64) error {
	db := r.db
	if tx != nil {
		db = tx
	}
	return db.WithContext(ctx).Delete(&entities.SaleDetail{}, id).Error
}

// FindDetailBySaleAndProductWithTx locates a line item matching both sale and product within a transaction scope.
func (r *saleRepository) FindDetailBySaleAndProductWithTx(ctx context.Context, tx *gorm.DB, saleID uint64, productID uint64) (*entities.SaleDetail, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var detail entities.SaleDetail
	err := db.WithContext(ctx).
		Where("sale_id = ? AND product_id = ?", saleID, productID).
		First(&detail).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &detail, nil
}

// FindAllDetailsBySaleIDWithTx queries all line item details associated with a sale inside a transaction scope.
func (r *saleRepository) FindAllDetailsBySaleIDWithTx(ctx context.Context, tx *gorm.DB, saleID uint64) ([]entities.SaleDetail, error) {
	db := r.db
	if tx != nil {
		db = tx
	}
	var details []entities.SaleDetail
	err := db.WithContext(ctx).
		Where("sale_id = ?", saleID).
		Find(&details).Error
	if err != nil {
		return nil, err
	}
	return details, nil
}