// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (User / Auth Database Operations)
// Service: SupermarketService
// Target Concern: repositories

package repositories

import (
	"context"
	"errors"

	"gorm.io/gorm"
	"supermarket-backend/entities"
)

// UserRepository defines the database operations for User entities.
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram
type UserRepository interface {
	Create(ctx context.Context, user *entities.User) error
	FindByUsername(ctx context.Context, username string) (*entities.User, error)
	FindByID(ctx context.Context, id uint64) (*entities.User, error)
	Update(ctx context.Context, user *entities.User) error
	Delete(ctx context.Context, id uint64) error
	FindAll(ctx context.Context, offset, limit int) ([]entities.User, int64, error)
}

type userRepository struct {
	db *gorm.DB
}

// NewUserRepository creates a new UserRepository instance using GORM.
func NewUserRepository(db *gorm.DB) UserRepository {
	return &userRepository{db: db}
}

// Create inserts a new user record.
func (r *userRepository) Create(ctx context.Context, user *entities.User) error {
	return r.db.WithContext(ctx).Create(user).Error
}

// FindByUsername retrieves an active user by their username.
// Index used: idx_user_active (username, deleted_at)
func (r *userRepository) FindByUsername(ctx context.Context, username string) (*entities.User, error) {
	var user entities.User
	err := r.db.WithContext(ctx).Where("username = ?", username).First(&user).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &user, nil
}

// FindByID retrieves a user by their unique primary key.
func (r *userRepository) FindByID(ctx context.Context, id uint64) (*entities.User, error) {
	var user entities.User
	err := r.db.WithContext(ctx).First(&user, id).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &user, nil
}

// Update updates an existing user record.
func (r *userRepository) Update(ctx context.Context, user *entities.User) error {
	return r.db.WithContext(ctx).Save(user).Error
}

// Delete soft-deletes a user record by ID.
func (r *userRepository) Delete(ctx context.Context, id uint64) error {
	return r.db.WithContext(ctx).Delete(&entities.User{}, id).Error
}

// FindAll lists users with offset pagination and returns the total count.
func (r *userRepository) FindAll(ctx context.Context, offset, limit int) ([]entities.User, int64, error) {
	var users []entities.User
	var total int64

	// Count total records in active scope
	err := r.db.WithContext(ctx).Model(&entities.User{}).Count(&total).Error
	if err != nil {
		return nil, 0, err
	}

	// Fetch paginated records
	err = r.db.WithContext(ctx).Offset(offset).Limit(limit).Find(&users).Error
	if err != nil {
		return nil, 0, err
	}

	return users, total, nil
}
