// Code generated by FEP Exceptions Sub-Agent.
// Service Name: SupermarketService
// Contract ID: CTR-007
// LOW-LEVEL DESIGN REFERENCE: LLD_SupermarketService.md#section-8-exception--error-mapping

package exceptions

import (
	"errors"
	"fmt"
)

// AppError represents a domain-specific structured error in the application.
// It implements the standard Go error interface and can be serialized to JSON.
type AppError struct {
	ErrorCode  string `json:"error_code"`
	Message    string `json:"message"`
	HTTPStatus int    `json:"-"` // Omitted from JSON serialization, used strictly for HTTP response status codes
}

// Error returns the string representation of the error.
func (e *AppError) Error() string {
	return e.Message
}

// Is checks if the target error has the same ErrorCode as this AppError.
// This allows dynamic AppError instances (e.g. created via constructors with detailed messages)
// to be compared with sentinel values using standard errors.Is.
func (e *AppError) Is(target error) bool {
	var t *AppError
	if errors.As(target, &t) {
		return e.ErrorCode == t.ErrorCode
	}
	return false
}

var (
	// ErrValidationFailed represents a 400 Bad Request validation error
	ErrValidationFailed = &AppError{
		ErrorCode:  "VALIDATION_FAILED",
		Message:    "Validation error on fields",
		HTTPStatus: 400,
	}

	// ErrUnauthorized represents a 401 Unauthorized error
	ErrUnauthorized = &AppError{
		ErrorCode:  "UNAUTHORIZED",
		Message:    "Authentication required or token expired",
		HTTPStatus: 401,
	}

	// ErrForbidden represents a 403 Forbidden error
	ErrForbidden = &AppError{
		ErrorCode:  "ACCESS_DENIED",
		Message:    "Insufficient permissions to perform action",
		HTTPStatus: 403,
	}

	// ErrNotFound represents a 404 Not Found error
	ErrNotFound = &AppError{
		ErrorCode:  "RESOURCE_NOT_FOUND",
		Message:    "The requested resource was not found",
		HTTPStatus: 404,
	}

	// ErrConflict represents a 409 Conflict error
	ErrConflict = &AppError{
		ErrorCode:  "RESOURCE_ALREADY_EXISTS",
		Message:    "Database unique index violation on record",
		HTTPStatus: 409,
	}

	// ErrStockInsufficient represents a 409 Conflict error due to insufficient stock
	ErrStockInsufficient = &AppError{
		ErrorCode:  "STOCK_INSUFFICIENT",
		Message:    "Requested quantity exceeds available stock",
		HTTPStatus: 409,
	}

	// ErrInternal represents a 500 Internal Server error
	ErrInternal = &AppError{
		ErrorCode:  "INTERNAL_SERVER_ERROR",
		Message:    "An unexpected error occurred",
		HTTPStatus: 500,
	}
)

// NewValidationError creates a customized validation error with the specific fields that failed validation.
func NewValidationError(fields string) *AppError {
	return &AppError{
		ErrorCode:  "VALIDATION_FAILED",
		Message:    fmt.Sprintf("Validation error on fields: %s", fields),
		HTTPStatus: 400,
	}
}

// NewStockInsufficientError creates a customized stock error with the current available stock level.
func NewStockInsufficientError(availableStock int) *AppError {
	return &AppError{
		ErrorCode:  "STOCK_INSUFFICIENT",
		Message:    fmt.Sprintf("Requested quantity exceeds available stock (%d)", availableStock),
		HTTPStatus: 409,
	}
}

// NewUnauthorizedError creates a customized ErrUnauthorized with a custom context message if needed.
func NewUnauthorizedError(reason ...string) *AppError {
	msg := ErrUnauthorized.Message
	if len(reason) > 0 {
		msg = reason[0]
	}
	return &AppError{
		ErrorCode:  ErrUnauthorized.ErrorCode,
		Message:    msg,
		HTTPStatus: ErrUnauthorized.HTTPStatus,
	}
}

// NewForbiddenError creates a customized ErrForbidden with a custom context message if needed.
func NewForbiddenError(reason ...string) *AppError {
	msg := ErrForbidden.Message
	if len(reason) > 0 {
		msg = reason[0]
	}
	return &AppError{
		ErrorCode:  ErrForbidden.ErrorCode,
		Message:    msg,
		HTTPStatus: ErrForbidden.HTTPStatus,
	}
}

// NewNotFoundError creates a customized ErrNotFound with a custom resource description.
func NewNotFoundError(resourceAndID ...string) *AppError {
	msg := ErrNotFound.Message
	if len(resourceAndID) > 0 {
		msg = fmt.Sprintf("The requested resource was not found: %s", resourceAndID[0])
	}
	return &AppError{
		ErrorCode:  ErrNotFound.ErrorCode,
		Message:    msg,
		HTTPStatus: ErrNotFound.HTTPStatus,
	}
}

// NewConflictError creates a customized ErrConflict with a custom explanation.
func NewConflictError(explanation ...string) *AppError {
	msg := ErrConflict.Message
	if len(explanation) > 0 {
		msg = explanation[0]
	}
	return &AppError{
		ErrorCode:  ErrConflict.ErrorCode,
		Message:    msg,
		HTTPStatus: ErrConflict.HTTPStatus,
	}
}

// NewInternalError creates a customized ErrInternal with an underlying cause.
func NewInternalError(reason ...string) *AppError {
	msg := ErrInternal.Message
	if len(reason) > 0 {
		msg = reason[0]
	}
	return &AppError{
		ErrorCode:  ErrInternal.ErrorCode,
		Message:    msg,
		HTTPStatus: ErrInternal.HTTPStatus,
	}
}

// FromError attempts to convert a generic error to an AppError.
// If the error is already an AppError (or wraps one), it returns that AppError.
// If it is another type of error, it wraps it in an AppError with status 500 and code INTERNAL_SERVER_ERROR,
// but keeps the message of the error if it is safe, or defaults to the standard internal message.
func FromError(err error) *AppError {
	if err == nil {
		return nil
	}

	var appErr *AppError
	if errors.As(err, &appErr) {
		return appErr
	}

	// Default to internal error but preserve the underlying message for internal logging
	return &AppError{
		ErrorCode:  ErrInternal.ErrorCode,
		Message:    err.Error(),
		HTTPStatus: ErrInternal.HTTPStatus,
	}
}
