// Code generated by FEP Exceptions Sub-Agent.
// Service Name: SupermarketService
// Contract ID: CTR-007
// LOW-LEVEL DESIGN REFERENCE: LLD_SupermarketService.md#section-8-exception--error-mapping

package exceptions

import (
	"errors"
	"net"
	"net/http"
	"os"
	"runtime/debug"
	"strings"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

// ErrorResponse defines the standardized error response body structure returned to clients.
// This implements a consistent error envelope across all endpoints of SupermarketService.
type ErrorResponse struct {
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

// ErrorHandlerMiddleware intercepts any errors registered on the Gin context via c.Error(err).
// It converts them to AppError, sets the correct HTTP status code, serializes the standardized
// ErrorResponse JSON body, and logs the occurrence using the shared Zap structured logger.
func ErrorHandlerMiddleware(logger *zap.Logger) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Next()

		// Only process if there are accumulated errors in the request context
		if len(c.Errors) > 0 {
			// Extract the last error recorded
			ginErr := c.Errors.Last()
			err := ginErr.Err

			// Convert to our structured AppError format
			appErr := FromError(err)

			// Determine log level: Warning for client errors, Error for server/internal errors
			if appErr.HTTPStatus >= 500 {
				logger.Error("Server error encountered during request execution",
					zap.String("error_code", appErr.ErrorCode),
					zap.String("message", appErr.Message),
					zap.Int("http_status", appErr.HTTPStatus),
					zap.String("path", c.Request.URL.Path),
					zap.String("method", c.Request.Method),
					zap.Error(err),
				)
			} else {
				logger.Warn("Client error returned by request handler",
					zap.String("error_code", appErr.ErrorCode),
					zap.String("message", appErr.Message),
					zap.Int("http_status", appErr.HTTPStatus),
					zap.String("path", c.Request.URL.Path),
					zap.String("method", c.Request.Method),
					zap.Error(err),
				)
			}

			// Render standard error envelope with correct HTTP Status
			c.JSON(appErr.HTTPStatus, ErrorResponse{
				ErrorCode: appErr.ErrorCode,
				Message:    appErr.Message,
			})

			// Abort the request execution chain to prevent downstream handler executions
			c.Abort()
		}
	}
}

// RecoveryMiddleware handles unexpected panics gracefully during the request-response lifecycle.
// It intercepts panics, logs full diagnostics and stack traces securely via the Zap structured logger,
// and protects the application from leaking internal memory layout or stack traces to external clients
// by returning a generic HTTP 500 internal server error.
func RecoveryMiddleware(logger *zap.Logger) gin.HandlerFunc {
	return func(c *gin.Context) {
		defer func() {
			if rval := recover(); rval != nil {
				// Check for broken connection to avoid writing back response on aborted sockets
				var brokenPipe bool
				if ne, ok := rval.(*net.OpError); ok {
					var se *os.SyscallError
					if errors.As(ne.Err, &se) {
						errStr := strings.ToLower(se.Error())
						if strings.Contains(errStr, "broken pipe") || strings.Contains(errStr, "connection reset by peer") {
							brokenPipe = true
						}
					}
				}

				// Log recovery details securely (with stack trace for debugging)
				logger.Error("Recovery middleware intercepted an unhandled panic",
					zap.Any("panic_value", rval),
					zap.String("path", c.Request.URL.Path),
					zap.String("method", c.Request.Method),
					zap.String("stack", string(debug.Stack())),
				)

				if brokenPipe {
					// If the connection is broken, we cannot write a response, so we abort and return
					_ = c.Error(errors.New("broken network pipe encountered during panic recovery"))
					c.Abort()
					return
				}

				// Build safe response conforming to the security posture: zero internal info leaked
				c.JSON(http.StatusInternalServerError, ErrorResponse{
					ErrorCode: ErrInternal.ErrorCode,
					Message:    ErrInternal.Message,
				})
				c.Abort()
			}
		}()
		c.Next()
	}
}