// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Category Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// CategoryController handles HTTP requests for product categories.
type CategoryController struct {
	categoryService services.CategoryService
}

// NewCategoryController creates a new instance of CategoryController.
func NewCategoryController(categoryService services.CategoryService) *CategoryController {
	return &CategoryController{
		categoryService: categoryService,
	}
}

// CreateCategory creates a new product category.
// @Summary Create Category
// @Description Register a new unique product category. ADMIN or INVENTORY role required.
// @Tags Categories
// @Accept json
// @Produce json
// @Param request body dto.CreateCategoryReq true "Category details"
// @Success 201 {object} dto.CategoryResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 409 {object} exceptions.ErrorResponse "Category already exists"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories [post]
func (ctrl *CategoryController) CreateCategory(c *gin.Context) {
	var req dto.CreateCategoryReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.categoryService.CreateCategory(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// ListCategories lists all categories with pagination and optional search filter.
// @Summary List Categories
// @Description List categories in alphabetical order with pagination and name filter.
// @Tags Categories
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Param filter query string false "Alphabetical prefix or substring filter"
// @Success 200 {object} dto.PaginatedCategories
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories [get]
func (ctrl *CategoryController) ListCategories(c *gin.Context) {
	page, size := getPaginationParams(c)
	filter := c.Query("filter")

	res, err := ctrl.categoryService.ListCategories(c.Request.Context(), page, size, filter)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetCategoryByID retrieves details for a single category.
// @Summary Get Category Details
// @Description Retrieve category by unique identifier.
// @Tags Categories
// @Accept json
// @Produce json
// @Param id path int true "Category ID"
// @Success 200 {object} dto.CategoryResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories/{id} [get]
func (ctrl *CategoryController) GetCategoryByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid category ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.categoryService.GetCategoryByID(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdateCategory updates an existing category.
// @Summary Update Category
// @Description Modify category details. ADMIN or INVENTORY role required.
// @Tags Categories
// @Accept json
// @Produce json
// @Param id path int true "Category ID"
// @Param request body dto.UpdateCategoryReq true "Updated details"
// @Success 200 {object} dto.CategoryResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories/{id} [put]
func (ctrl *CategoryController) UpdateCategory(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid category ID format"))
		c.Abort()
		return
	}

	var req dto.UpdateCategoryReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.categoryService.UpdateCategory(c.Request.Context(), id, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// DeleteCategory soft-deletes a category.
// @Summary Delete Category
// @Description Soft-delete category and trigger cascading deletion of products inside. ADMIN only.
// @Tags Categories
// @Accept json
// @Produce json
// @Param id path int true "Category ID"
// @Success 204 "No Content"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories/{id} [delete]
func (ctrl *CategoryController) DeleteCategory(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid category ID format"))
		c.Abort()
		return
	}

	err = ctrl.categoryService.DeleteCategory(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.Status(http.StatusNoContent)
}

// ListCategoryProducts lists active products belonging to a category.
// @Summary List Category Products
// @Description Retrieve a paginated list of active products belonging to the specified category.
// @Tags Categories
// @Accept json
// @Produce json
// @Param id path int true "Category ID"
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Success 200 {object} dto.PaginatedProducts
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/categories/{id}/products [get]
func (ctrl *CategoryController) ListCategoryProducts(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid category ID format"))
		c.Abort()
		return
	}

	page, size := getPaginationParams(c)

	res, err := ctrl.categoryService.ListCategoryProducts(c.Request.Context(), id, page, size)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}