// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Client Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// ClientController handles HTTP requests for client registration and management.
type ClientController struct {
	clientService services.ClientService
}

// NewClientController creates a new instance of ClientController.
func NewClientController(clientService services.ClientService) *ClientController {
	return &ClientController{
		clientService: clientService,
	}
}

// CreateClient registers a new client in the supermarket system.
// @Summary Register Client
// @Description Register a new customer with mandatory Name, DNI, and Email validations. ADMIN or CASHIER role required.
// @Tags Clients
// @Accept json
// @Produce json
// @Param request body dto.CreateClientReq true "Client registration details"
// @Success 201 {object} dto.ClientResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 409 {object} exceptions.ErrorResponse "Client with this DNI already exists"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients [post]
func (ctrl *ClientController) CreateClient(c *gin.Context) {
	var req dto.CreateClientReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.clientService.CreateClient(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// ListClients retrieves a paginated list of clients with optional filters.
// @Summary List Clients
// @Description Retrieve registered customers with pagination. Optional filters for DNI and Email. ADMIN or CASHIER role required.
// @Tags Clients
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Param dni query string false "Filter by DNI"
// @Param email query string false "Filter by Email"
// @Success 200 {object} dto.PaginatedClients
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients [get]
func (ctrl *ClientController) ListClients(c *gin.Context) {
	page, size := getPaginationParams(c)
	dni := c.Query("dni")
	email := c.Query("email")

	res, err := ctrl.clientService.ListClients(c.Request.Context(), page, size, dni, email)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetClientByID retrieves a customer record by its ID.
// @Summary Get Client details
// @Description Retrieve client record details. ADMIN or CASHIER role required.
// @Tags Clients
// @Accept json
// @Produce json
// @Param id path int true "Client ID"
// @Success 200 {object} dto.ClientResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients/{id} [get]
func (ctrl *ClientController) GetClientByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid client ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.clientService.GetClientByID(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdateClient updates client details.
// @Summary Update Client Details
// @Description Modify customer records. ADMIN or CASHIER role required.
// @Tags Clients
// @Accept json
// @Produce json
// @Param id path int true "Client ID"
// @Param request body dto.UpdateClientReq true "Updated details"
// @Success 200 {object} dto.ClientResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients/{id} [put]
func (ctrl *ClientController) UpdateClient(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid client ID format"))
		c.Abort()
		return
	}

	var req dto.UpdateClientReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.clientService.UpdateClient(c.Request.Context(), id, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// DeleteClient soft-deletes a client.
// @Summary Delete Client Record
// @Description Soft-delete customer profile from checkout POS. ADMIN only.
// @Tags Clients
// @Accept json
// @Produce json
// @Param id path int true "Client ID"
// @Success 204 "No Content"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients/{id} [delete]
func (ctrl *ClientController) DeleteClient(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid client ID format"))
		c.Abort()
		return
	}

	err = ctrl.clientService.DeleteClient(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.Status(http.StatusNoContent)
}

// SearchClient searches for a client by DNI or Email.
// @Summary Fast Search Client
// @Description Find unique customer records directly by DNI or Email queries. ADMIN or CASHIER role required.
// @Tags Clients
// @Accept json
// @Produce json
// @Param dni query string false "National ID (DNI)"
// @Param email query string false "Email address"
// @Success 200 {object} dto.ClientResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure (missing search fields)"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/clients/search [get]
func (ctrl *ClientController) SearchClient(c *gin.Context) {
	dni := c.Query("dni")
	email := c.Query("email")

	if dni == "" && email == "" {
		c.Error(exceptions.NewValidationError("Either 'dni' or 'email' query parameter must be provided"))
		c.Abort()
		return
	}

	res, err := ctrl.clientService.SearchClient(c.Request.Context(), dni, email)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}
