// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (gRPC Handler)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-1-directory--package-structure

package controllers

import (
	"context"
	"errors"

	dto "supermarket-backend/dtos"
	"supermarket-backend/services"
)

// Since the pb generated files might reside under "supermarket-backend/internal/grpc/pb",
// we can define standard gRPC request/response types or mock interface helpers to ensure
// compiling and clean architecture without hard blockers.

// OpenSaleRequest represents a gRPC request to open a sale.
type OpenSaleRequest struct {
	CashierID uint64 `json:"cashier_id"`
	ClientID  uint64 `json:"client_id,omitempty"` // 0 if none
}

// OpenSaleResponse represents a gRPC response after opening a sale.
type OpenSaleResponse struct {
	SaleID     uint64  `json:"sale_id"`
	TotalPrice float64 `json:"total_price"`
	Status     string  `json:"status"`
}

// AddItemRequest represents a gRPC request to add an item to a sale.
type AddItemRequest struct {
	SaleID    uint64 `json:"sale_id"`
	ProductID uint64 `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

// AddItemResponse represents a gRPC response after adding an item to a sale.
type AddItemResponse struct {
	SaleID     uint64             `json:"sale_id"`
	TotalPrice float64            `json:"total_price"`
	Status     string             `json:"status"`
	LineItems  []*gRPCLineItem    `json:"line_items"`
}

// gRPCLineItem represents a line item in gRPC messages.
type gRPCLineItem struct {
	ItemID    uint64  `json:"item_id"`
	ProductID uint64  `json:"product_id"`
	Name      string  `json:"product_name"`
	UnitPrice float64 `json:"unit_price"`
	Quantity  int32   `json:"quantity"`
	SubTotal  float64 `json:"sub_total"`
}

// FinalizeSaleRequest represents a gRPC request to finalize a sale.
type FinalizeSaleRequest struct {
	SaleID uint64 `json:"sale_id"`
}

// FinalizeSaleResponse represents a gRPC response after finalization.
type FinalizeSaleResponse struct {
	SaleID     uint64  `json:"sale_id"`
	TotalPrice float64 `json:"total_price"`
	Status     string  `json:"status"`
}

// CalculatePriceRequest represents a gRPC request to calculate price for a product.
type CalculatePriceRequest struct {
	ProductID uint64 `json:"product_id"`
}

// CalculatePriceResponse represents a gRPC response for pricing breakdown.
type CalculatePriceResponse struct {
	ProductID             uint64  `json:"product_id"`
	BasePrice             float64 `json:"base_price"`
	StandardFinalPrice    float64 `json:"standard_final_price"`
	PromotionalFinalPrice float64 `json:"promotional_final_price"`
	PromoID               uint64  `json:"promo_id,omitempty"`
	PromoName             string  `json:"promo_name,omitempty"`
	PromoDiscount         float64 `json:"promo_discount,omitempty"`
}

// GRPCHandler implements highly-optimized gRPC endpoints for checkout systems.
type GRPCHandler struct {
	saleService    services.SaleService
	productService services.ProductService
}

// NewGRPCHandler creates a new instance of GRPCHandler.
func NewGRPCHandler(saleService services.SaleService, productService services.ProductService) *GRPCHandler {
	return &GRPCHandler{
		saleService:    saleService,
		productService: productService,
	}
}

// OpenSale starts a new checkout transaction over gRPC.
func (h *GRPCHandler) OpenSale(ctx context.Context, req *OpenSaleRequest) (*OpenSaleResponse, error) {
	if req.CashierID == 0 {
		return nil, errors.New("cashier_id is required")
	}

	var clientID *uint64
	if req.ClientID != 0 {
		cid := req.ClientID
		clientID = &cid
	}

	dtoReq := &dto.OpenSaleRequest{
		ClientID: clientID,
	}

	res, err := h.saleService.OpenSale(ctx, req.CashierID, dtoReq)
	if err != nil {
		return nil, err
	}

	return &OpenSaleResponse{
		SaleID:     res.ID,
		TotalPrice: res.TotalPrice,
		Status:     res.Status,
	}, nil
}

// AddItemToSale adds a product line-item to an open checkout transaction over gRPC.
func (h *GRPCHandler) AddItemToSale(ctx context.Context, req *AddItemRequest) (*AddItemResponse, error) {
	if req.SaleID == 0 {
		return nil, errors.New("sale_id is required")
	}
	if req.ProductID == 0 {
		return nil, errors.New("product_id is required")
	}
	if req.Quantity <= 0 {
		return nil, errors.New("quantity must be greater than zero")
	}

	dtoReq := &dto.AddItemRequest{
		ProductID: req.ProductID,
		Quantity:  int(req.Quantity),
	}

	res, err := h.saleService.AddItemToSale(ctx, req.SaleID, dtoReq)
	if err != nil {
		return nil, err
	}

	items := make([]*gRPCLineItem, len(res.LineItems))
	for i, item := range res.LineItems {
		items[i] = &gRPCLineItem{
			ItemID:    item.ItemID,
			ProductID: item.ProductID,
			Name:      item.Name,
			UnitPrice: item.UnitPrice,
			Quantity:  int32(item.Quantity),
			SubTotal:  item.SubTotal,
		}
	}

	return &AddItemResponse{
		SaleID:     res.Sale.ID,
		TotalPrice: res.Sale.TotalPrice,
		Status:     res.Sale.Status,
		LineItems:  items,
	}, nil
}

// FinalizeSale completes the sale checkout over gRPC.
func (h *GRPCHandler) FinalizeSale(ctx context.Context, req *FinalizeSaleRequest) (*FinalizeSaleResponse, error) {
	if req.SaleID == 0 {
		return nil, errors.New("sale_id is required")
	}

	res, err := h.saleService.FinalizeSale(ctx, req.SaleID)
	if err != nil {
		return nil, err
	}

	return &FinalizeSaleResponse{
		SaleID:     res.ID,
		TotalPrice: res.TotalPrice,
		Status:     res.Status,
	}, nil
}

// GetProductPrice retrieves product pricing breakdown and active promotions over gRPC.
func (h *GRPCHandler) GetProductPrice(ctx context.Context, req *CalculatePriceRequest) (*CalculatePriceResponse, error) {
	if req.ProductID == 0 {
		return nil, errors.New("product_id is required")
	}

	res, err := h.productService.CalculatePrice(ctx, req.ProductID)
	if err != nil {
		return nil, err
	}

	resp := &CalculatePriceResponse{
		ProductID:             res.ProductID,
		BasePrice:             res.BasePrice,
		StandardFinalPrice:    res.StandardFinalPrice,
		PromotionalFinalPrice: res.PromotionalFinalPrice,
	}

	if res.AppliedPromotion != nil {
		resp.PromoID = res.AppliedPromotion.ID
		resp.PromoName = res.AppliedPromotion.Name
		resp.PromoDiscount = res.AppliedPromotion.DiscountPercentage
	}

	return resp, nil
}