// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Product Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// ProductController handles HTTP requests for product catalog and inventory.
type ProductController struct {
	productService services.ProductService
}

// NewProductController creates a new instance of ProductController.
func NewProductController(productService services.ProductService) *ProductController {
	return &ProductController{
		productService: productService,
	}
}

// CreateProduct registers a new product in the catalog.
// @Summary Create Product
// @Description Register a new product. ADMIN or INVENTORY role required.
// @Tags Products
// @Accept json
// @Produce json
// @Param request body dto.CreateProductReq true "Product registration details"
// @Success 201 {object} dto.ProductResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 409 {object} exceptions.ErrorResponse "Product already exists"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products [post]
func (ctrl *ProductController) CreateProduct(c *gin.Context) {
	var req dto.CreateProductReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.productService.CreateProduct(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// ListProducts retrieves a paginated list of active products.
// @Summary List Products
// @Description Retrieve registered active products with pagination and optional name query filter.
// @Tags Products
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Param name query string false "Filter products by name"
// @Success 200 {object} dto.PaginatedProducts
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products [get]
func (ctrl *ProductController) ListProducts(c *gin.Context) {
	page, size := getPaginationParams(c)
	name := c.Query("name")

	res, err := ctrl.productService.ListProducts(c.Request.Context(), page, size, name)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetProductByID retrieves single product details.
// @Summary Get Product details
// @Description Retrieve catalog profile of a product by ID.
// @Tags Products
// @Accept json
// @Produce json
// @Param id path int true "Product ID"
// @Success 200 {object} dto.ProductResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products/{id} [get]
func (ctrl *ProductController) GetProductByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.productService.GetProductByID(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdateProduct updates product details in the catalog.
// @Summary Update Product details
// @Description Modify product records. ADMIN or INVENTORY role required.
// @Tags Products
// @Accept json
// @Produce json
// @Param id path int true "Product ID"
// @Param request body dto.UpdateProductReq true "Updated product details"
// @Success 200 {object} dto.ProductResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products/{id} [put]
func (ctrl *ProductController) UpdateProduct(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	var req dto.UpdateProductReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.productService.UpdateProduct(c.Request.Context(), id, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// DeleteProduct soft-deletes a product.
// @Summary Delete Product
// @Description Soft-delete a product from the catalog. ADMIN only.
// @Tags Products
// @Accept json
// @Produce json
// @Param id path int true "Product ID"
// @Success 204 "No Content"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products/{id} [delete]
func (ctrl *ProductController) DeleteProduct(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	err = ctrl.productService.DeleteProduct(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.Status(http.StatusNoContent)
}

// RestockProduct atomically increases a product's stock levels.
// @Summary Restock Product
// @Description Restock inventory quantity atomically. ADMIN or INVENTORY role required.
// @Tags Products
// @Accept json
// @Produce json
// @Param id path int true "Product ID"
// @Param request body dto.RestockReq true "Restock details"
// @Success 200 {object} dto.ProductResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products/{id}/restock [post]
func (ctrl *ProductController) RestockProduct(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	var req dto.RestockReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.productService.RestockProduct(c.Request.Context(), id, req.Quantity)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetProductPrice retrieves product pricing breakdown including active promotions.
// @Summary Calculate Price Breakdown
// @Description Retrieve base price, standard final consumer price, active promotions and discounted final consumer price.
// @Tags Products
// @Accept json
// @Produce json
// @Param id path int true "Product ID"
// @Success 200 {object} dto.PriceBreakdownResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/products/{id}/price [get]
func (ctrl *ProductController) GetProductPrice(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.productService.CalculatePrice(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}