// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Promotion Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// PromotionController handles HTTP requests for managing promotional campaigns.
type PromotionController struct {
	promotionService services.PromotionService
}

// NewPromotionController creates a new instance of PromotionController.
func NewPromotionController(promotionService services.PromotionService) *PromotionController {
	return &PromotionController{
		promotionService: promotionService,
	}
}

// CreatePromotion registers a new promotion campaign.
// @Summary Configure Promotion
// @Description Register a new promotion campaign with custom dates and active discount percentage. ADMIN or INVENTORY role required.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param request body dto.CreatePromotionReq true "Promotion campaign details"
// @Success 201 {object} dto.PromotionResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions [post]
func (ctrl *PromotionController) CreatePromotion(c *gin.Context) {
	var req dto.CreatePromotionReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.promotionService.CreatePromotion(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// ListPromotions lists active promotions with pagination.
// @Summary List Promotions
// @Description List active and registered promotions.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Success 200 {object} dto.PaginatedPromotions
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions [get]
func (ctrl *PromotionController) ListPromotions(c *gin.Context) {
	page, size := getPaginationParams(c)

	res, err := ctrl.promotionService.ListPromotions(c.Request.Context(), page, size)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetPromotionByID retrieves single campaign details.
// @Summary Get Promotion details
// @Description Retrieve details of a promotion by unique identifier.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param id path int true "Promotion ID"
// @Success 200 {object} dto.PromotionResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions/{id} [get]
func (ctrl *PromotionController) GetPromotionByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid promotion ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.promotionService.GetPromotionByID(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdatePromotion updates an existing promotion campaign.
// @Summary Update Promotion details
// @Description Modify campaign details such as name, discount percentage, and boundary dates. ADMIN or INVENTORY role required.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param id path int true "Promotion ID"
// @Param request body dto.UpdatePromotionReq true "Updated campaign details"
// @Success 200 {object} dto.PromotionResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions/{id} [put]
func (ctrl *PromotionController) UpdatePromotion(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid promotion ID format"))
		c.Abort()
		return
	}

	var req dto.UpdatePromotionReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.promotionService.UpdatePromotion(c.Request.Context(), id, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// DeletePromotion soft-deletes a promotion campaign.
// @Summary Delete Promotion Campaign
// @Description Soft-delete campaign and remove active price mappings. ADMIN only.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param id path int true "Promotion ID"
// @Success 204 "No Content"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions/{id} [delete]
func (ctrl *PromotionController) DeletePromotion(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid promotion ID format"))
		c.Abort()
		return
	}

	err = ctrl.promotionService.DeletePromotion(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.Status(http.StatusNoContent)
}

// LinkProductsToPromotion links multiple products to an active campaign.
// @Summary Link Products to Promotion
// @Description Link a batch of products to the Specified campaign. ADMIN or INVENTORY role required.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param id path int true "Promotion ID"
// @Param request body dto.LinkProductsReq true "Batch product IDs"
// @Success 200 {object} dto.SimpleMsg
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions/{id}/products [post]
func (ctrl *PromotionController) LinkProductsToPromotion(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid promotion ID format"))
		c.Abort()
		return
	}

	var req dto.LinkProductsReq
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	err = ctrl.promotionService.LinkProductsToPromotion(c.Request.Context(), id, req.ProductIDs)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, dto.SimpleMsg{Message: "Products linked successfully"})
}

// UnlinkProductFromPromotion removes a product's association with a campaign.
// @Summary Unlink Product from Promotion
// @Description Unlink product from campaign to restore standard pricing. ADMIN only.
// @Tags Promotions
// @Accept json
// @Produce json
// @Param id path int true "Promotion ID"
// @Param productId path int true "Product ID"
// @Success 200 {object} dto.SimpleMsg
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/promotions/{id}/products/{productId} [delete]
func (ctrl *PromotionController) UnlinkProductFromPromotion(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid promotion ID format"))
		c.Abort()
		return
	}

	prodIDStr := c.Param("productId")
	prodID, err := strconv.ParseUint(prodIDStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid product ID format"))
		c.Abort()
		return
	}

	err = ctrl.promotionService.UnlinkProductFromPromotion(c.Request.Context(), id, prodID)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, dto.SimpleMsg{Message: "Product unlinked successfully"})
}