// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Router Registration)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-1-directory--package-structure

package controllers

import (
	"supermarket-backend/exceptions"
	"supermarket-backend/middleware"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"

	_ "supermarket-backend/docs"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// RegisterRoutes configures all the endpoints of the SupermarketService,
// wrapping handlers with global exception, panic-recovery, and security middleware.
func RegisterRoutes(
	r *gin.Engine,
	userCtrl *UserController,
	catCtrl *CategoryController,
	clientCtrl *ClientController,
	prodCtrl *ProductController,
	promoCtrl *PromotionController,
	saleCtrl *SaleController,
	logger *zap.Logger,
	authMiddleware gin.HandlerFunc, // JWT parsing and injection
	roleGuard func(allowedRoles ...string) gin.HandlerFunc, // Role enforcement middleware builder
	ownerOrAdminGuard gin.HandlerFunc, // Resource ownership enforcement (self or ADMIN)
	allowedOrigins []string, // CORS allow-list
) {
	// Register global middleware
	r.Use(middleware.LoggerMiddleware(logger))
	r.Use(exceptions.RecoveryMiddleware(logger))
	r.Use(exceptions.ErrorHandlerMiddleware(logger))
	r.Use(middleware.NewCORSMiddleware(allowedOrigins))

	// Rate limiting: 100 requests per second with burst capacity of 20
	rateLimiter := middleware.NewIPRateLimiter(100.0, 20.0)
	r.Use(rateLimiter.Limit())

	// Liveness/readiness probe - intentionally unauthenticated and outside /api/v0.0
	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok"})
	})

	// Swagger API Docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Base API V0.0 Router Group (Aligned with Legacy Java Codebase)
	v0 := r.Group("/api/v0.0")
	{
		// ----------------------------------------------------
		// Users / Auth Domain
		// ----------------------------------------------------
		auth := v0.Group("/auth")
		{
			// Public login
			auth.POST("/login", userCtrl.LoginUser)

			// Authenticated auth actions
			auth.Use(authMiddleware)
			{
				// Admin-only register operator
				auth.POST("/register", roleGuard("ADMIN"), userCtrl.RegisterUser)
				
				// Logout (Any operator)
				auth.POST("/logout", userCtrl.LogoutUser)
			}
		}

		users := v0.Group("/users")
		users.Use(authMiddleware)
		{
			// Admin-only list operators
			users.GET("", roleGuard("ADMIN"), userCtrl.ListUsers)

			// Operator retrieval and update (Self or ADMIN protected)
			selfOrAdmin := users.Group("")
			selfOrAdmin.Use(ownerOrAdminGuard)
			{
				selfOrAdmin.GET("/:id", userCtrl.GetUserByID)
				selfOrAdmin.PUT("/:id", userCtrl.UpdateUser)
			}

			// Admin-only soft delete operator profile
			users.DELETE("/:id", roleGuard("ADMIN"), userCtrl.DeleteUser)
		}

		// ----------------------------------------------------
		// Categories Domain
		// ----------------------------------------------------
		categories := v0.Group("/categories")
		categories.Use(authMiddleware)
		{
			// Reading catalog for any logged-in operator
			categories.GET("", catCtrl.ListCategories)
			categories.GET("/:id", catCtrl.GetCategoryByID)
			categories.GET("/:id/products", catCtrl.ListCategoryProducts)

			// Modify operations (ADMIN or INVENTORY)
			inventoryMod := categories.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", catCtrl.CreateCategory)
				inventoryMod.PUT("/:id", catCtrl.UpdateCategory)
			}

			// Admin-only soft delete
			categories.DELETE("/:id", roleGuard("ADMIN"), catCtrl.DeleteCategory)
		}

		// ----------------------------------------------------
		// Clients Domain
		// ----------------------------------------------------
		clients := v0.Group("/clients")
		clients.Use(authMiddleware)
		{
			// Read/Write access (ADMIN or CASHIER)
			cashierAndAdmin := clients.Group("")
			cashierAndAdmin.Use(roleGuard("ADMIN", "CASHIER"))
			{
				cashierAndAdmin.POST("", clientCtrl.CreateClient)
				cashierAndAdmin.GET("", clientCtrl.ListClients)
				cashierAndAdmin.GET("/search", clientCtrl.SearchClient)
				cashierAndAdmin.GET("/dni/:dni", clientCtrl.GetClientByDNI) // Aligned with legacy Java DNI path
				cashierAndAdmin.GET("/:id", clientCtrl.GetClientByID)
				cashierAndAdmin.PUT("/:id", clientCtrl.UpdateClient)
			}

			// Admin-only soft delete
			clients.DELETE("/:id", roleGuard("ADMIN"), clientCtrl.DeleteClient)
		}

		// ----------------------------------------------------
		// Products Domain
		// ----------------------------------------------------
		products := v0.Group("/products")
		products.Use(authMiddleware)
		{
			// Read catalog prices and details (All operators)
			products.GET("", prodCtrl.ListProducts)
			products.GET("/:id", prodCtrl.GetProductByID)
			products.GET("/:id/price", prodCtrl.GetProductPrice)

			// Catalog management and Restocking (ADMIN or INVENTORY)
			inventoryMod := products.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", prodCtrl.CreateProduct)
				inventoryMod.PUT("/:id", prodCtrl.UpdateProduct)
				inventoryMod.PATCH("/:id/restock", prodCtrl.RestockProduct) // Aligned with legacy Java PATCH RESTOCK
			}

			// Admin-only soft delete
			products.DELETE("/:id", roleGuard("ADMIN"), prodCtrl.DeleteProduct)
		}

		// ----------------------------------------------------
		// Promotions Domain
		// ----------------------------------------------------
		promotions := v0.Group("/promotions")
		promotions.Use(authMiddleware)
		{
			// Read campaign details (All operators)
			promotions.GET("", promoCtrl.ListPromotions)
			promotions.GET("/:id", promoCtrl.GetPromotionByID)

			// Campaign setups and linking (ADMIN or INVENTORY)
			inventoryMod := promotions.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", promoCtrl.CreatePromotion)
				inventoryMod.PUT("/:id", promoCtrl.UpdatePromotion)
				inventoryMod.POST("/:id/products", promoCtrl.LinkProductsToPromotion)
			}

			// Admin-only delete and unlink campaign associations
			adminOnly := promotions.Group("")
			adminOnly.Use(roleGuard("ADMIN"))
			{
				adminOnly.DELETE("/:id", promoCtrl.DeletePromotion)
				adminOnly.DELETE("/:id/products/:productId", promoCtrl.UnlinkProductFromPromotion)
			}
		}

		// ----------------------------------------------------
		// POS Checkout Sales Domain
		// ----------------------------------------------------
		sales := v0.Group("/sales")
		sales.Use(authMiddleware)
		{
			// POS operations (ADMIN or CASHIER)
			posOps := sales.Group("")
			posOps.Use(roleGuard("ADMIN", "CASHIER"))
			{
				posOps.POST("", saleCtrl.OpenSale)
				posOps.GET("", saleCtrl.ListSales)
				posOps.GET("/:id", saleCtrl.GetSaleByID)
				posOps.POST("/:id/details", saleCtrl.AddItemToSale) // Aligned with legacy Java /details endpoint
				posOps.PATCH("/:id/finalize", saleCtrl.FinalizeSale) // Aligned with legacy Java PATCH FINALIZE
				posOps.DELETE("/:id", saleCtrl.CancelSale) // Aligned with legacy Java DELETE CANCEL

				// Sale Details Management Sub-module
				posOps.PUT("/details/:id", saleCtrl.UpdateItemQuantity) // Aligned with legacy Java /details/{id} endpoint
				posOps.DELETE("/details/:id", saleCtrl.RemoveItemFromSale) // Aligned with legacy Java /details/{id} endpoint
				posOps.GET("/details/:id", saleCtrl.GetSaleDetailByID) // Aligned with legacy Java /details/{id} endpoint
			}
		}
	}
}