// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Router Registration)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-1-directory--package-structure

package controllers

import (
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	"supermarket-backend/exceptions"
	"supermarket-backend/middleware"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "supermarket-backend/docs"
)

// RegisterRoutes configures all the endpoints of the SupermarketService,
// wrapping handlers with global exception, panic-recovery, and security middleware.
func RegisterRoutes(
	r *gin.Engine,
	userCtrl *UserController,
	catCtrl *CategoryController,
	clientCtrl *ClientController,
	prodCtrl *ProductController,
	promoCtrl *PromotionController,
	saleCtrl *SaleController,
	logger *zap.Logger,
	authMiddleware gin.HandlerFunc,                         // JWT parsing and injection
	roleGuard func(allowedRoles ...string) gin.HandlerFunc, // Role enforcement middleware builder
	ownerOrAdminGuard gin.HandlerFunc,                      // Resource ownership enforcement (self or ADMIN)
	allowedOrigins []string,                                // CORS allow-list
) {
	// Register global middleware
	r.Use(middleware.LoggerMiddleware(logger))
	r.Use(exceptions.RecoveryMiddleware(logger))
	r.Use(exceptions.ErrorHandlerMiddleware(logger))
	r.Use(middleware.NewCORSMiddleware(allowedOrigins))

	// Rate limiting: 100 requests per second with burst capacity of 20
	rateLimiter := middleware.NewIPRateLimiter(100.0, 20.0)
	r.Use(rateLimiter.Limit())

	// Liveness/readiness probe - intentionally unauthenticated and outside /api/v1
	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "ok"})
	})

	// Swagger API Docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Base API V1 Router Group
	v1 := r.Group("/api/v1")
	{
		// ----------------------------------------------------
		// Users / Auth Domain
		// ----------------------------------------------------
		users := v1.Group("/users")
		{
			// Public login
			users.POST("/login", userCtrl.LoginUser)

			// Authenticated routes
			users.Use(authMiddleware)
			{
				// Logout (Any operator)
				users.POST("/logout", userCtrl.LogoutUser)

				// Operator retrieval and update (Self or ADMIN protected)
				selfOrAdmin := users.Group("")
				selfOrAdmin.Use(ownerOrAdminGuard)
				{
					selfOrAdmin.GET("/:id", userCtrl.GetUserByID)
					selfOrAdmin.PUT("/:id", userCtrl.UpdateUser)
				}

				// Admin-only endpoints
				adminOnly := users.Group("")
				adminOnly.Use(roleGuard("ADMIN"))
				{
					adminOnly.POST("", userCtrl.RegisterUser)
					adminOnly.GET("", userCtrl.ListUsers)
					adminOnly.DELETE("/:id", userCtrl.DeleteUser)
				}
			}
		}

		// ----------------------------------------------------
		// Categories Domain
		// ----------------------------------------------------
		categories := v1.Group("/categories")
		categories.Use(authMiddleware)
		{
			// Public catalog reading for any logged in operator
			categories.GET("", catCtrl.ListCategories)
			categories.GET("/:id", catCtrl.GetCategoryByID)
			categories.GET("/:id/products", catCtrl.ListCategoryProducts)

			// Modify operations (ADMIN or INVENTORY)
			inventoryMod := categories.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", catCtrl.CreateCategory)
				inventoryMod.PUT("/:id", catCtrl.UpdateCategory)
			}

			// Admin-only soft delete
			adminOnlyDelete := categories.Group("")
			adminOnlyDelete.Use(roleGuard("ADMIN"))
			adminOnlyDelete.DELETE("/:id", catCtrl.DeleteCategory)
		}

		// ----------------------------------------------------
		// Clients Domain
		// ----------------------------------------------------
		clients := v1.Group("/clients")
		clients.Use(authMiddleware)
		{
			// Read/Write access (ADMIN or CASHIER)
			cashierAndAdmin := clients.Group("")
			cashierAndAdmin.Use(roleGuard("ADMIN", "CASHIER"))
			{
				cashierAndAdmin.POST("", clientCtrl.CreateClient)
				cashierAndAdmin.GET("", clientCtrl.ListClients)
				cashierAndAdmin.GET("/search", clientCtrl.SearchClient)
				cashierAndAdmin.GET("/:id", clientCtrl.GetClientByID)
				cashierAndAdmin.PUT("/:id", clientCtrl.UpdateClient)
			}

			// Admin-only soft delete
			adminOnlyDelete := clients.Group("")
			adminOnlyDelete.Use(roleGuard("ADMIN"))
			adminOnlyDelete.DELETE("/:id", clientCtrl.DeleteClient)
		}

		// ----------------------------------------------------
		// Products Domain
		// ----------------------------------------------------
		products := v1.Group("/products")
		products.Use(authMiddleware)
		{
			// Read catalog prices and details (All operators)
			products.GET("", prodCtrl.ListProducts)
			products.GET("/:id", prodCtrl.GetProductByID)
			products.GET("/:id/price", prodCtrl.GetProductPrice)

			// Catalog management and Restocking (ADMIN or INVENTORY)
			inventoryMod := products.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", prodCtrl.CreateProduct)
				inventoryMod.PUT("/:id", prodCtrl.UpdateProduct)
				inventoryMod.POST("/:id/restock", prodCtrl.RestockProduct)
			}

			// Admin-only soft delete
			adminOnlyDelete := products.Group("")
			adminOnlyDelete.Use(roleGuard("ADMIN"))
			adminOnlyDelete.DELETE("/:id", prodCtrl.DeleteProduct)
		}

		// ----------------------------------------------------
		// Promotions Domain
		// ----------------------------------------------------
		promotions := v1.Group("/promotions")
		promotions.Use(authMiddleware)
		{
			// Read campaign details (All operators)
			promotions.GET("", promoCtrl.ListPromotions)
			promotions.GET("/:id", promoCtrl.GetPromotionByID)

			// Campaign setups and linking (ADMIN or INVENTORY)
			inventoryMod := promotions.Group("")
			inventoryMod.Use(roleGuard("ADMIN", "INVENTORY"))
			{
				inventoryMod.POST("", promoCtrl.CreatePromotion)
				inventoryMod.PUT("/:id", promoCtrl.UpdatePromotion)
				inventoryMod.POST("/:id/products", promoCtrl.LinkProductsToPromotion)
			}

			// Admin-only delete and unlink campaign associations
			adminOnly := promotions.Group("")
			adminOnly.Use(roleGuard("ADMIN"))
			{
				adminOnly.DELETE("/:id", promoCtrl.DeletePromotion)
				adminOnly.DELETE("/:id/products/:productId", promoCtrl.UnlinkProductFromPromotion)
			}
		}

		// ----------------------------------------------------
		// POS Checkout Sales Domain
		// ----------------------------------------------------
		sales := v1.Group("/sales")
		sales.Use(authMiddleware)
		{
			// POS operations (ADMIN or CASHIER)
			posOps := sales.Group("")
			posOps.Use(roleGuard("ADMIN", "CASHIER"))
			{
				posOps.POST("", saleCtrl.OpenSale)
				posOps.GET("", saleCtrl.ListSales)
				posOps.GET("/:id", saleCtrl.GetSaleByID)
				posOps.POST("/:id/items", saleCtrl.AddItemToSale)
				posOps.PUT("/:id/items/:itemId", saleCtrl.UpdateItemQuantity)
				posOps.DELETE("/:id/items/:itemId", saleCtrl.RemoveItemFromSale)
				posOps.POST("/:id/finalize", saleCtrl.FinalizeSale)
				posOps.POST("/:id/cancel", saleCtrl.CancelSale)
			}
		}
	}
}
