// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (Sale Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// SaleController handles HTTP requests for Point of Sale (POS) checkouts and transactions.
type SaleController struct {
	saleService services.SaleService
}

// NewSaleController creates a new instance of SaleController.
func NewSaleController(saleService services.SaleService) *SaleController {
	return &SaleController{
		saleService: saleService,
	}
}

// OpenSale initiates a new active checkout transaction.
// @Summary Open Sale Transaction
// @Description Open a new checkout transaction in the system. Cashier ID is injected from JWT claims. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param request body dto.OpenSaleRequest true "Optional associated customer ID"
// @Success 201 {object} dto.SaleResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales [post]
func (ctrl *SaleController) OpenSale(c *gin.Context) {
	var req dto.OpenSaleRequest
	// Optional request body, don't strictly require json structure if empty, but bind if present
	if c.Request.ContentLength > 0 {
		if err := c.ShouldBindJSON(&req); err != nil {
			c.Error(exceptions.NewValidationError(err.Error()))
			c.Abort()
			return
		}
	}

	cashierID := getOperatorID(c)
	if cashierID == 0 {
		c.Error(exceptions.NewUnauthorizedError("Cashier ID could not be retrieved from authenticated token"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.OpenSale(c.Request.Context(), cashierID, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// ListSales retrieves sales transactions based on filters.
// @Summary List Sales History
// @Description Retrieve sales history with pagination. Optional filters for status, client ID, and cashier ID. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Param status query string false "Filter by sale status (e.g. ACTIVE, FINALIZED, CANCELLED)"
// @Param clientId query string false "Filter by client ID"
// @Param cashierId query string false "Filter by cashier ID"
// @Success 200 {object} dto.PaginatedSales
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales [get]
func (ctrl *SaleController) ListSales(c *gin.Context) {
	page, size := getPaginationParams(c)
	status := c.Query("status")
	clientID := c.Query("clientId")
	cashierID := c.Query("cashierId")

	var clID *uint64
	if clientID != "" {
		if val, err := strconv.ParseUint(clientID, 10, 64); err == nil {
			clID = &val
		} else {
			c.Error(exceptions.NewValidationError("Invalid client ID format"))
			c.Abort()
			return
		}
	}

	var csID *uint64
	if cashierID != "" {
		if val, err := strconv.ParseUint(cashierID, 10, 64); err == nil {
			csID = &val
		} else {
			c.Error(exceptions.NewValidationError("Invalid cashier ID format"))
			c.Abort()
			return
		}
	}

	res, err := ctrl.saleService.ListSales(c.Request.Context(), page, size, status, clID, csID)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetSaleByID retrieves a detailed breakdown of a sale including its line items.
// @Summary Get Detailed Sale
// @Description Retrieve complete transaction details including line items. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Sale ID"
// @Success 200 {object} dto.SaleDetailResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/{id} [get]
func (ctrl *SaleController) GetSaleByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid sale ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.GetSaleByID(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// AddItemToSale adds a product line-item to an open sale.
// @Summary Add Item to Sale
// @Description Add a line item of a product. Performs pessimistic stock locks and computes price before updating total. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Sale ID"
// @Param request body dto.AddItemRequest true "Item addition details"
// @Success 200 {object} dto.SaleDetailResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 409 {object} exceptions.ErrorResponse "Stock insufficient or Sale is not active"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/{id}/details [post]
func (ctrl *SaleController) AddItemToSale(c *gin.Context) {
	idStr := c.Param("id")
	saleID, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid sale ID format"))
		c.Abort()
		return
	}

	var req dto.AddItemRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.AddItemToSale(c.Request.Context(), saleID, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdateItemQuantity modifies the purchased quantity of a line item.
// @Summary Update Item Quantity
// @Description Modify purchased units of an existing line item. Adjusts stock levels atomically. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Line Item ID"
// @Param request body dto.UpdateItemQtyRequest true "Updated quantity details"
// @Success 200 {object} dto.SaleDetailResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 409 {object} exceptions.ErrorResponse "Stock insufficient or Sale is finalized/cancelled"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/details/{id} [put]
func (ctrl *SaleController) UpdateItemQuantity(c *gin.Context) {
	itemIDStr := c.Param("id")
	itemID, err := strconv.ParseUint(itemIDStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid item ID format"))
		c.Abort()
		return
	}

	var req dto.UpdateItemQtyRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.UpdateItemQuantity(c.Request.Context(), 0, itemID, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// RemoveItemFromSale removes a line item from the transaction and restores product stock levels.
// @Summary Remove Item from Sale
// @Description Remove product line item and release locked stock atomically. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Line Item ID"
// @Success 200 {object} dto.SaleDetailResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/details/{id} [delete]
func (ctrl *SaleController) RemoveItemFromSale(c *gin.Context) {
	itemIDStr := c.Param("id")
	itemID, err := strconv.ParseUint(itemIDStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid item ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.RemoveItemFromSale(c.Request.Context(), 0, itemID)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// FinalizeSale completes the sale transaction.
// @Summary Finalize Sale
// @Description Finalize the sale transaction, marking it completed and freezing total price calculations. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Sale ID"
// @Success 200 {object} dto.SaleResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/{id}/finalize [patch]
func (ctrl *SaleController) FinalizeSale(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid sale ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.FinalizeSale(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// CancelSale terminates the sale transaction and restores all product inventory stock levels.
// @Summary Cancel Sale
// @Description Cancel the active sale transaction and atomically restock all products associated. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Sale ID"
// @Success 200 {object} dto.SaleResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/{id} [delete]
func (ctrl *SaleController) CancelSale(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid sale ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.CancelSale(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetSaleDetailByID retrieves details of a single line item.
// @Summary Get Line Item Details
// @Description Retrieve details of a single line item in an open sale. ADMIN or CASHIER role required.
// @Tags Sales
// @Accept json
// @Produce json
// @Param id path int true "Line Item ID"
// @Success 200 {object} dto.LineItemResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/sales/details/{id} [get]
func (ctrl *SaleController) GetSaleDetailByID(c *gin.Context) {
	itemIDStr := c.Param("id")
	itemID, err := strconv.ParseUint(itemIDStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid item ID format"))
		c.Abort()
		return
	}

	res, err := ctrl.saleService.GetSaleDetailByID(c.Request.Context(), itemID)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}