// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-001 (User / Auth Controller)
// Service Name: SupermarketService
// Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram

package controllers

import (
	"net/http"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"
	dto "supermarket-backend/dtos"
	"supermarket-backend/exceptions"
	"supermarket-backend/services"
)

// UserController handles HTTP requests for user and authentication management.
type UserController struct {
	userService services.UserService
}

// NewUserController creates a new instance of UserController.
func NewUserController(userService services.UserService) *UserController {
	return &UserController{
		userService: userService,
	}
}

// RegisterUser registers a new operator in the system.
// @Summary Register Operator
// @Description Register a new operator (ADMIN, CASHIER, INVENTORY) with password hashing.
// @Tags Users
// @Accept json
// @Produce json
// @Param request body dto.RegisterRequest true "Registration details"
// @Success 201 {object} dto.UserResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 409 {object} exceptions.ErrorResponse "Username already exists"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users [post]
func (ctrl *UserController) RegisterUser(c *gin.Context) {
	var req dto.RegisterRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.userService.RegisterUser(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusCreated, res)
}

// LoginUser authenticates an operator and issues a JWT token.
// @Summary Operator Login
// @Description Authenticate operator credentials and return a session token.
// @Tags Users
// @Accept json
// @Produce json
// @Param request body dto.LoginRequest true "Login credentials"
// @Success 200 {object} dto.LoginResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized credentials"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users/login [post]
func (ctrl *UserController) LoginUser(c *gin.Context) {
	var req dto.LoginRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	res, err := ctrl.userService.LoginUser(c.Request.Context(), &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// LogoutUser revokes the current operator's session.
// @Summary Operator Logout
// @Description Revoke active operator session by blacklisting the JWT token.
// @Tags Users
// @Accept json
// @Produce json
// @Success 200 {object} dto.SimpleMsg
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users/logout [post]
func (ctrl *UserController) LogoutUser(c *gin.Context) {
	authHeader := c.GetHeader("Authorization")
	if authHeader == "" {
		c.Error(exceptions.NewUnauthorizedError("Authorization header is required"))
		c.Abort()
		return
	}

	parts := strings.SplitN(authHeader, " ", 2)
	var token string
	if len(parts) == 2 && strings.ToLower(parts[0]) == "bearer" {
		token = parts[1]
	} else {
		token = authHeader
	}

	err := ctrl.userService.LogoutUser(c.Request.Context(), token)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, dto.SimpleMsg{Message: "Logout successful"})
}

// ListUsers retrieves a paginated list of all operators.
// @Summary List Operators
// @Description Retrieve operators with limit/offset pagination. Admin only.
// @Tags Users
// @Accept json
// @Produce json
// @Param page query int false "Page number" default(1)
// @Param size query int false "Page size" default(10)
// @Success 200 {object} dto.PaginatedUsers
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users [get]
func (ctrl *UserController) ListUsers(c *gin.Context) {
	page, size := getPaginationParams(c)

	res, err := ctrl.userService.ListUsers(c.Request.Context(), page, size)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// GetUserByID retrieves an operator profile by its ID.
// @Summary Get Operator Profile
// @Description Retrieve operator profile. Accessible to owner and ADMIN only.
// @Tags Users
// @Accept json
// @Produce json
// @Param id path int true "Operator ID"
// @Success 200 {object} dto.UserResponse
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden (Access Denied)"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users/{id} [get]
func (ctrl *UserController) GetUserByID(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid user ID format"))
		c.Abort()
		return
	}

	reqUserID := getOperatorID(c)
	reqRole := getOperatorRole(c)

	res, err := ctrl.userService.GetUserByID(c.Request.Context(), id, reqUserID, reqRole)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// UpdateUser updates an operator's profile details.
// @Summary Update Operator Profile
// @Description Modify operator profile. Accessible to owner and ADMIN only.
// @Tags Users
// @Accept json
// @Produce json
// @Param id path int true "Operator ID"
// @Param request body dto.UpdateUserRequest true "Update payload"
// @Success 200 {object} dto.UserResponse
// @Failure 400 {object} exceptions.ErrorResponse "Validation failure"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden (Access Denied)"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v1/users/{id} [put]
func (ctrl *UserController) UpdateUser(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid user ID format"))
		c.Abort()
		return
	}

	var req dto.UpdateUserRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.Error(exceptions.NewValidationError(err.Error()))
		c.Abort()
		return
	}

	reqUserID := getOperatorID(c)
	reqRole := getOperatorRole(c)

	res, err := ctrl.userService.UpdateUser(c.Request.Context(), id, reqUserID, reqRole, &req)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.JSON(http.StatusOK, res)
}

// DeleteUser performs a soft-delete of an operator.
// @Summary Delete Operator
// @Description Soft-delete operator profile by setting deleted_at. ADMIN only.
// @Tags Users
// @Accept json
// @Produce json
// @Param id path int true "Operator ID"
// @Success 204 "No Content"
// @Failure 401 {object} exceptions.ErrorResponse "Unauthorized"
// @Failure 403 {object} exceptions.ErrorResponse "Forbidden"
// @Failure 404 {object} exceptions.ErrorResponse "Not Found"
// @Failure 500 {object} exceptions.ErrorResponse "Internal Server Error"
// @Router /api/v0.0/users/{id} [delete]
func (ctrl *UserController) DeleteUser(c *gin.Context) {
	idStr := c.Param("id")
	id, err := strconv.ParseUint(idStr, 10, 64)
	if err != nil {
		c.Error(exceptions.NewValidationError("Invalid user ID format"))
		c.Abort()
		return
	}

	err = ctrl.userService.DeleteUser(c.Request.Context(), id)
	if err != nil {
		c.Error(err)
		c.Abort()
		return
	}

	c.Status(http.StatusNoContent)
}

// Helpers for request parsing inside the package

func getPaginationParams(c *gin.Context) (int, int) {
	pageStr := c.DefaultQuery("page", "1")
	sizeStr := c.DefaultQuery("size", "10")

	page, err := strconv.Atoi(pageStr)
	if err != nil || page < 1 {
		page = 1
	}

	size, err := strconv.Atoi(sizeStr)
	if err != nil || size < 1 {
		size = 10
	}

	return page, size
}

func getOperatorID(c *gin.Context) uint64 {
	keys := []string{"OperatorID", "operatorID", "operator_id", "userId", "userID", "user_id"}
	for _, key := range keys {
		if val, exists := c.Get(key); exists {
			switch v := val.(type) {
			case uint64:
				return v
			case int:
				return uint64(v)
			case int64:
				return uint64(v)
			case float64:
				return uint64(v)
			case string:
				if parsed, err := strconv.ParseUint(v, 10, 64); err == nil {
					return parsed
				}
			}
		}
	}
	return 0
}

func getOperatorRole(c *gin.Context) string {
	keys := []string{"Role", "role"}
	for _, key := range keys {
		if val, exists := c.Get(key); exists {
			if s, ok := val.(string); ok {
				return s
			}
		}
	}
	return ""
}