// Code generated by FEP sub-agent.
// Service Name: SupermarketService
// Description: Missing service interfaces to enable complete and successful compilation of controllers.

package services

import (
	"context"
	dto "supermarket-backend/dtos"
)

// ClientService defines business-logic capabilities for handling Client management.
type ClientService interface {
	CreateClient(ctx context.Context, req *dto.CreateClientReq) (*dto.ClientResponse, error)
	ListClients(ctx context.Context, page, size int, dni, email string) (*dto.PaginatedClients, error)
	GetClientByID(ctx context.Context, id uint64) (*dto.ClientResponse, error)
	UpdateClient(ctx context.Context, id uint64, req *dto.UpdateClientReq) (*dto.ClientResponse, error)
	DeleteClient(ctx context.Context, id uint64) error
	SearchClient(ctx context.Context, dni, email string) (*dto.ClientResponse, error)
}

// UserService defines business-logic capabilities for handling operators and auth.
type UserService interface {
	RegisterUser(ctx context.Context, req *dto.RegisterRequest) (*dto.UserResponse, error)
	LoginUser(ctx context.Context, req *dto.LoginRequest) (*dto.LoginResponse, error)
	LogoutUser(ctx context.Context, token string) error
	ListUsers(ctx context.Context, page, size int) (*dto.PaginatedUsers, error)
	GetUserByID(ctx context.Context, id uint64, reqUserID uint64, reqRole string) (*dto.UserResponse, error)
	UpdateUser(ctx context.Context, id uint64, reqUserID uint64, reqRole string, req *dto.UpdateUserRequest) (*dto.UserResponse, error)
	DeleteUser(ctx context.Context, id uint64) error
}

// ProductService defines business-logic capabilities for handling product catalog.
type ProductService interface {
	CreateProduct(ctx context.Context, req *dto.CreateProductReq) (*dto.ProductResponse, error)
	ListProducts(ctx context.Context, page, size int, name string) (*dto.PaginatedProducts, error)
	GetProductByID(ctx context.Context, id uint64) (*dto.ProductResponse, error)
	UpdateProduct(ctx context.Context, id uint64, req *dto.UpdateProductReq) (*dto.ProductResponse, error)
	DeleteProduct(ctx context.Context, id uint64) error
	RestockProduct(ctx context.Context, id uint64, quantity int) (*dto.ProductResponse, error)
	CalculatePrice(ctx context.Context, id uint64) (*dto.PriceBreakdownResponse, error)
}

// CategoryService defines business-logic capabilities for handling product categories.
type CategoryService interface {
	CreateCategory(ctx context.Context, req *dto.CreateCategoryReq) (*dto.CategoryResponse, error)
	ListCategories(ctx context.Context, page, size int, filter string) (*dto.PaginatedCategories, error)
	GetCategoryByID(ctx context.Context, id uint64) (*dto.CategoryResponse, error)
	UpdateCategory(ctx context.Context, id uint64, req *dto.UpdateCategoryReq) (*dto.CategoryResponse, error)
	DeleteCategory(ctx context.Context, id uint64) error
	ListCategoryProducts(ctx context.Context, categoryID uint64, page, size int) (*dto.PaginatedProducts, error)
}

// PromotionService defines business-logic capabilities for handling discount campaigns.
type PromotionService interface {
	CreatePromotion(ctx context.Context, req *dto.CreatePromotionReq) (*dto.PromotionResponse, error)
	ListPromotions(ctx context.Context, page, size int) (*dto.PaginatedPromotions, error)
	GetPromotionByID(ctx context.Context, id uint64) (*dto.PromotionResponse, error)
	UpdatePromotion(ctx context.Context, id uint64, req *dto.UpdatePromotionReq) (*dto.PromotionResponse, error)
	DeletePromotion(ctx context.Context, id uint64) error
	LinkProductsToPromotion(ctx context.Context, id uint64, productIDs []uint64) error
	UnlinkProductFromPromotion(ctx context.Context, id uint64, productID uint64) error
}