// Code generated by FEP sub-agent.
// Service Name: SupermarketService
// Contract ID: CTR-002
// LOW-LEVEL DESIGN REFERENCE: LLD_SupermarketService.md#section-4-class-diagram

package services

import (
	"context"
	"errors"
	"math"
	"time"

	"gorm.io/gorm"
	dto "supermarket-backend/dtos"
	"supermarket-backend/entities"
	"supermarket-backend/exceptions"
	"supermarket-backend/repositories"
)

// SaleService defines business-logic capabilities for handling Point of Sale checkout transactions.
// Contract Traceability:
// - Implements design_contracts.json contract CTR-002.
// - Service Name: SupermarketService
// - Low-Level Design Reference: LLD_SupermarketService.md#section-4-class-diagram
type SaleService interface {
	OpenSale(ctx context.Context, cashierID uint64, req *dto.OpenSaleRequest) (*dto.SaleResponse, error)
	ListSales(ctx context.Context, page, size int, status string, clID, csID *uint64) (*dto.PaginatedSales, error)
	GetSaleByID(ctx context.Context, id uint64) (*dto.SaleDetailResponse, error)
	AddItemToSale(ctx context.Context, saleID uint64, req *dto.AddItemRequest) (*dto.SaleDetailResponse, error)
	UpdateItemQuantity(ctx context.Context, saleID, itemID uint64, req *dto.UpdateItemQtyRequest) (*dto.SaleDetailResponse, error)
	RemoveItemFromSale(ctx context.Context, saleID, itemID uint64) (*dto.SaleDetailResponse, error)
	FinalizeSale(ctx context.Context, id uint64) (*dto.SaleResponse, error)
	CancelSale(ctx context.Context, id uint64) (*dto.SaleResponse, error)
	GetSaleDetailByID(ctx context.Context, id uint64) (*dto.LineItemResponse, error)
}

type saleServiceImpl struct {
	saleRepo    repositories.SaleRepository
	productRepo repositories.ProductRepository
	db          *gorm.DB
}

// NewSaleService constructs a new SaleService implementation.
func NewSaleService(saleRepo repositories.SaleRepository, productRepo repositories.ProductRepository, db *gorm.DB) SaleService {
	return &saleServiceImpl{
		saleRepo:    saleRepo,
		productRepo: productRepo,
		db:          db,
	}
}

// RoundHalfUp performs double precision rounding to exactly 2 decimals using standard HALF_UP rule.
func RoundHalfUp(val float64) float64 {
	return math.Round(val*100.0) / 100.0
}

// OpenSale initiates a new POS transaction.
func (s *saleServiceImpl) OpenSale(ctx context.Context, cashierID uint64, req *dto.OpenSaleRequest) (*dto.SaleResponse, error) {
	sale := &entities.Sale{
		Status:     "OPEN",
		TotalPrice: 0.0,
		CashierID:  cashierID,
		CreatedAt:  time.Now(),
	}
	if req != nil && req.ClientID != nil && *req.ClientID != 0 {
		sale.ClientID = req.ClientID
	}

	if err := s.saleRepo.CreateSale(ctx, s.db, sale); err != nil {
		return nil, exceptions.NewInternalError("Failed to open sale: " + err.Error())
	}

	return &dto.SaleResponse{
		ID:         sale.ID,
		TotalPrice: sale.TotalPrice,
		Status:     sale.Status,
		ClientID:   sale.ClientID,
		CashierID:  sale.CashierID,
		CreatedAt:  sale.CreatedAt,
	}, nil
}

// GetSaleByID retrieves details of an existing sale.
func (s *saleServiceImpl) GetSaleByID(ctx context.Context, id uint64) (*dto.SaleDetailResponse, error) {
	sale, err := s.saleRepo.FindSaleByID(ctx, id)
	if err != nil {
		return nil, exceptions.NewInternalError("Failed to fetch sale: " + err.Error())
	}
	if sale == nil {
		return nil, exceptions.NewNotFoundError("Sale transaction not found")
	}

	return s.assembleSaleDetailResponse(ctx, sale, sale.Details)
}

// ListSales fetches a paginated and filtered history of transactions.
func (s *saleServiceImpl) ListSales(ctx context.Context, page, size int, status string, clID, csID *uint64) (*dto.PaginatedSales, error) {
	if page <= 0 {
		page = 1
	}
	if size <= 0 {
		size = 10
	}
	offset := (page - 1) * size

	sales, total, err := s.saleRepo.FindSales(ctx, offset, size, status, clID, csID)
	if err != nil {
		return nil, exceptions.NewInternalError("Failed to list sales: " + err.Error())
	}

	items := make([]dto.SaleResponse, len(sales))
	for i, sale := range sales {
		items[i] = dto.SaleResponse{
			ID:         sale.ID,
			TotalPrice: sale.TotalPrice,
			Status:     sale.Status,
			ClientID:   sale.ClientID,
			CashierID:  sale.CashierID,
			FinishedAt: sale.FinishedAt,
			CreatedAt:  sale.CreatedAt,
		}
	}

	return &dto.PaginatedSales{
		Items:      items,
		TotalCount: total,
	}, nil
}

// AddItemToSale adds a product line-item to an open sale transaction using a pessimistic lock on the product stock.
func (s *saleServiceImpl) AddItemToSale(ctx context.Context, saleID uint64, req *dto.AddItemRequest) (*dto.SaleDetailResponse, error) {
	var response *dto.SaleDetailResponse

	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Verify parent Sale exists and status is OPEN (lock row pessimistic)
		sale, err := s.saleRepo.FindSaleByIDWithLock(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Database error during sale lookup: " + err.Error())
		}
		if sale == nil {
			return exceptions.NewNotFoundError("Sale transaction not found")
		}
		if sale.Status != "OPEN" {
			return exceptions.NewConflictError("Cannot add line-item items to a non-OPEN sale")
		}

		// 2. Retrieve Product and lock to prevent concurrent races
		product, err := s.productRepo.FindByIDWithLock(ctx, tx, req.ProductID)
		if err != nil {
			return exceptions.NewInternalError("Database error during product lookup: " + err.Error())
		}
		if product == nil {
			return exceptions.NewNotFoundError("Product not found or soft-deleted")
		}

		// 3. Atomically check if inventory stock is sufficient
		if product.Stock < req.Quantity {
			return exceptions.NewStockInsufficientError(product.Stock)
		}

		// 4. Calculate unit price utilizing the Promotion & Tax engines
		unitPrice, err := s.calculateProductConsumerPrice(ctx, tx, product)
		if err != nil {
			return err
		}

		// 5. Decrement inventory level atomically inside product database record
		newStock := product.Stock - req.Quantity
		if err := s.productRepo.UpdateStockWithTx(ctx, tx, product.ID, newStock); err != nil {
			return exceptions.NewInternalError("Failed to update product stock: " + err.Error())
		}

		// 6. Calculate subtotal for line item
		subtotal := RoundHalfUp(unitPrice * float64(req.Quantity))

		// 7. Persist or increment SaleDetail item
		existingDetail, err := s.saleRepo.FindDetailBySaleAndProductWithTx(ctx, tx, saleID, product.ID)
		if err != nil {
			return exceptions.NewInternalError("Database error during line item check: " + err.Error())
		}

		if existingDetail != nil {
			// Update quantity and recalculate subtotal on existing line item
			existingDetail.Quantity += req.Quantity
			existingDetail.SubTotal = RoundHalfUp(existingDetail.UnitPrice * float64(existingDetail.Quantity))
			if err := s.saleRepo.UpdateDetailWithTx(ctx, tx, existingDetail); err != nil {
				return exceptions.NewInternalError("Failed to update line item: " + err.Error())
			}
		} else {
			// Create brand new sale detail line item
			newDetail := &entities.SaleDetail{
				SaleID:    saleID,
				ProductID: product.ID,
				UnitPrice: unitPrice,
				Quantity:  req.Quantity,
				SubTotal:  subtotal,
			}
			if err := s.saleRepo.CreateDetailWithTx(ctx, tx, newDetail); err != nil {
				return exceptions.NewInternalError("Failed to create line item: " + err.Error())
			}
		}

		// 8. Re-evaluate total_price on parent sale record
		allDetails, err := s.saleRepo.FindAllDetailsBySaleIDWithTx(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Failed to retrieve updated sale details: " + err.Error())
		}

		var newTotal float64 = 0.0
		for _, det := range allDetails {
			newTotal += det.SubTotal
		}
		sale.TotalPrice = RoundHalfUp(newTotal)
		if err := s.saleRepo.UpdateSaleWithTx(ctx, tx, sale); err != nil {
			return exceptions.NewInternalError("Failed to update sale total price: " + err.Error())
		}

		// Preload product relationships on details for Response payload assembly
		for i, det := range allDetails {
			if det.ProductID == product.ID {
				allDetails[i].Product = *product
			} else {
				prod, err := s.productRepo.FindByID(ctx, det.ProductID)
				if err != nil {
					return exceptions.NewInternalError("Failed to find product during response payload assembly: " + err.Error())
				}
				if prod != nil {
					allDetails[i].Product = *prod
				}
			}
		}

		// 9. Prepare return payloads
		var assembleErr error
		response, assembleErr = s.assembleSaleDetailResponse(ctx, sale, allDetails)
		if assembleErr != nil {
			return assembleErr
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return response, nil
}

// UpdateItemQuantity modifies an item's quantity in an open sale, adjusting inventory stock difference accordingly.
func (s *saleServiceImpl) UpdateItemQuantity(ctx context.Context, saleID, itemID uint64, req *dto.UpdateItemQtyRequest) (*dto.SaleDetailResponse, error) {
	var response *dto.SaleDetailResponse

	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if saleID == 0 {
			var detail entities.SaleDetail
			if err := tx.WithContext(ctx).First(&detail, itemID).Error; err != nil {
				if errors.Is(err, gorm.ErrRecordNotFound) {
					return exceptions.NewNotFoundError("Sale detail not found")
				}
				return exceptions.NewInternalError("Database error fetching sale detail: " + err.Error())
			}
			saleID = detail.SaleID
		}

		// 1. Verify parent sale is open
		sale, err := s.saleRepo.FindSaleByIDWithLock(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Database error during sale lookup: " + err.Error())
		}
		if sale == nil {
			return exceptions.NewNotFoundError("Sale transaction not found")
		}
		if sale.Status != "OPEN" {
			return exceptions.NewConflictError("Cannot update line-item items on a non-OPEN sale")
		}

		// 2. Fetch specific sale detail line item inside transaction
		var detail entities.SaleDetail
		err = tx.WithContext(ctx).Preload("Product").First(&detail, itemID).Error
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return exceptions.NewNotFoundError("Sale detail not found")
			}
			return exceptions.NewInternalError("Database error fetching sale detail: " + err.Error())
		}
		if detail.SaleID != saleID {
			return exceptions.NewConflictError("Sale detail does not belong to this sale transaction")
		}

		// 3. Lock associated product to prevent race conditions
		product, err := s.productRepo.FindByIDWithLock(ctx, tx, detail.ProductID)
		if err != nil {
			return exceptions.NewInternalError("Database error during product lock: " + err.Error())
		}
		if product == nil {
			return exceptions.NewNotFoundError("Associated product not found")
		}

		// 4. Calculate stock difference
		qtyDiff := req.Quantity - detail.Quantity
		if qtyDiff > 0 {
			// Increasing quantity, need to verify and deduct more stock
			if product.Stock < qtyDiff {
				return exceptions.NewStockInsufficientError(product.Stock)
			}
		}

		// 5. Update product stock level atomically
		newStock := product.Stock - qtyDiff
		if err := s.productRepo.UpdateStockWithTx(ctx, tx, product.ID, newStock); err != nil {
			return exceptions.NewInternalError("Failed to update product stock: " + err.Error())
		}

		// 6. Update sale detail quantity and subtotal
		detail.Quantity = req.Quantity
		detail.SubTotal = RoundHalfUp(detail.UnitPrice * float64(detail.Quantity))
		if err := s.saleRepo.UpdateDetailWithTx(ctx, tx, &detail); err != nil {
			return exceptions.NewInternalError("Failed to update sale detail: " + err.Error())
		}

		// 7. Re-evaluate total_price on parent sale record
		allDetails, err := s.saleRepo.FindAllDetailsBySaleIDWithTx(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Failed to fetch sale details: " + err.Error())
		}

		var newTotal float64 = 0.0
		for _, det := range allDetails {
			if det.ID == detail.ID {
				newTotal += detail.SubTotal
			} else {
				newTotal += det.SubTotal
			}
		}
		sale.TotalPrice = RoundHalfUp(newTotal)
		if err := s.saleRepo.UpdateSaleWithTx(ctx, tx, sale); err != nil {
			return exceptions.NewInternalError("Failed to update sale total price: " + err.Error())
		}

		// Preload product relationships on details for response payload assembly
		for i, det := range allDetails {
			if det.ID == detail.ID {
				allDetails[i] = detail
			} else {
				prod, err := s.productRepo.FindByID(ctx, det.ProductID)
				if err != nil {
					return exceptions.NewInternalError("Failed to find product during response payload assembly: " + err.Error())
				}
				if prod != nil {
					allDetails[i].Product = *prod
				}
			}
		}

		var assembleErr error
		response, assembleErr = s.assembleSaleDetailResponse(ctx, sale, allDetails)
		if assembleErr != nil {
			return assembleErr
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return response, nil
}

// RemoveItemFromSale deletes a line-item from an open sale, restocking the product stock level.
func (s *saleServiceImpl) RemoveItemFromSale(ctx context.Context, saleID, itemID uint64) (*dto.SaleDetailResponse, error) {
	var response *dto.SaleDetailResponse

	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if saleID == 0 {
			var detail entities.SaleDetail
			if err := tx.WithContext(ctx).First(&detail, itemID).Error; err != nil {
				if errors.Is(err, gorm.ErrRecordNotFound) {
					return exceptions.NewNotFoundError("Sale detail not found")
				}
				return exceptions.NewInternalError("Database error fetching sale detail: " + err.Error())
			}
			saleID = detail.SaleID
		}

		// 1. Verify parent sale is open
		sale, err := s.saleRepo.FindSaleByIDWithLock(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Database error during sale lookup: " + err.Error())
		}
		if sale == nil {
			return exceptions.NewNotFoundError("Sale transaction not found")
		}
		if sale.Status != "OPEN" {
			return exceptions.NewConflictError("Cannot remove line-item from a non-OPEN sale")
		}

		// 2. Fetch specific sale detail line item inside transaction
		var detail entities.SaleDetail
		err = tx.WithContext(ctx).Preload("Product").First(&detail, itemID).Error
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				return exceptions.NewNotFoundError("Sale detail not found")
			}
			return exceptions.NewInternalError("Database error fetching sale detail: " + err.Error())
		}
		if detail.SaleID != saleID {
			return exceptions.NewConflictError("Sale detail does not belong to this sale transaction")
		}

		// 3. Lock associated product to prevent race conditions
		product, err := s.productRepo.FindByIDWithLock(ctx, tx, detail.ProductID)
		if err != nil {
			return exceptions.NewInternalError("Database error during product lock: " + err.Error())
		}
		if product == nil {
			return exceptions.NewNotFoundError("Associated product not found")
		}

		// 4. Atomically restore/restock the product inventory level
		newStock := product.Stock + detail.Quantity
		if err := s.productRepo.UpdateStockWithTx(ctx, tx, product.ID, newStock); err != nil {
			return exceptions.NewInternalError("Failed to update product stock: " + err.Error())
		}

		// 5. Delete detail line item
		if err := s.saleRepo.DeleteDetail(ctx, tx, itemID); err != nil {
			return exceptions.NewInternalError("Failed to delete line item: " + err.Error())
		}

		// 6. Recalculate total_price on parent sale record
		allDetails, err := s.saleRepo.FindAllDetailsBySaleIDWithTx(ctx, tx, saleID)
		if err != nil {
			return exceptions.NewInternalError("Failed to fetch sale details: " + err.Error())
		}

		var remainingDetails []entities.SaleDetail
		var newTotal float64 = 0.0
		for _, det := range allDetails {
			if det.ID != itemID {
				newTotal += det.SubTotal
				prod, err := s.productRepo.FindByID(ctx, det.ProductID)
				if err != nil {
					return exceptions.NewInternalError("Failed to find product during response payload assembly: " + err.Error())
				}
				if prod != nil {
					det.Product = *prod
				}
				remainingDetails = append(remainingDetails, det)
			}
		}
		sale.TotalPrice = RoundHalfUp(newTotal)
		if err := s.saleRepo.UpdateSaleWithTx(ctx, tx, sale); err != nil {
			return exceptions.NewInternalError("Failed to update sale total price: " + err.Error())
		}

		var assembleErr error
		response, assembleErr = s.assembleSaleDetailResponse(ctx, sale, remainingDetails)
		if assembleErr != nil {
			return assembleErr
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return response, nil
}

// FinalizeSale closes an open transaction, verifying that it contains line-items.
func (s *saleServiceImpl) FinalizeSale(ctx context.Context, id uint64) (*dto.SaleResponse, error) {
	var response *dto.SaleResponse

	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Fetch parent sale with locking
		sale, err := s.saleRepo.FindSaleByIDWithLock(ctx, tx, id)
		if err != nil {
			return exceptions.NewInternalError("Database error during sale lookup: " + err.Error())
		}
		if sale == nil {
			return exceptions.NewNotFoundError("Sale transaction not found")
		}
		if sale.Status != "OPEN" {
			return exceptions.NewConflictError("Only OPEN sales can be finalized")
		}

		// 2. Verify that sale contains items
		details, err := s.saleRepo.FindAllDetailsBySaleIDWithTx(ctx, tx, id)
		if err != nil {
			return exceptions.NewInternalError("Failed to fetch sale details: " + err.Error())
		}
		if len(details) == 0 {
			return exceptions.NewValidationError("Cannot finalize an empty sale transaction")
		}

		// 3. Transition status to CLOSED and set finishedAt timestamp
		sale.Status = "CLOSED"
		now := time.Now()
		sale.FinishedAt = &now

		if err := s.saleRepo.UpdateSaleWithTx(ctx, tx, sale); err != nil {
			return exceptions.NewInternalError("Failed to update sale: " + err.Error())
		}

		response = &dto.SaleResponse{
			ID:         sale.ID,
			TotalPrice: sale.TotalPrice,
			Status:     sale.Status,
			ClientID:   sale.ClientID,
			CashierID:  sale.CashierID,
			FinishedAt: sale.FinishedAt,
			CreatedAt:  sale.CreatedAt,
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return response, nil
}

// CancelSale cancels an open transaction, restocking all products in sale details atomically.
func (s *saleServiceImpl) CancelSale(ctx context.Context, id uint64) (*dto.SaleResponse, error) {
	var response *dto.SaleResponse

	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// 1. Fetch parent sale with locking
		sale, err := s.saleRepo.FindSaleByIDWithLock(ctx, tx, id)
		if err != nil {
			return exceptions.NewInternalError("Database error during sale lookup: " + err.Error())
		}
		if sale == nil {
			return exceptions.NewNotFoundError("Sale transaction not found")
		}
		if sale.Status != "OPEN" {
			return exceptions.NewConflictError("Only OPEN sales can be cancelled")
		}

		// 2. Fetch all line items (SaleDetails)
		details, err := s.saleRepo.FindAllDetailsBySaleIDWithTx(ctx, tx, id)
		if err != nil {
			return exceptions.NewInternalError("Failed to fetch sale details: " + err.Error())
		}

		// 3. Loop through items to perform atomic restocking in MySQL
		for _, item := range details {
			product, err := s.productRepo.FindByIDWithLock(ctx, tx, item.ProductID)
			if err != nil {
				return exceptions.NewInternalError("Failed to lock product: " + err.Error())
			}
			if product == nil {
				return exceptions.NewNotFoundError("Product not found or corrupt")
			}
			newStock := product.Stock + item.Quantity
			if err := s.productRepo.UpdateStockWithTx(ctx, tx, product.ID, newStock); err != nil {
				return exceptions.NewInternalError("Failed to restock product stock: " + err.Error())
			}
		}

		// 4. Update parent status to CANCELED and set finished_at timestamp
		sale.Status = "CANCELED"
		now := time.Now()
		sale.FinishedAt = &now
		if err := s.saleRepo.UpdateSaleWithTx(ctx, tx, sale); err != nil {
			return exceptions.NewInternalError("Failed to update sale: " + err.Error())
		}

		response = &dto.SaleResponse{
			ID:         sale.ID,
			TotalPrice: sale.TotalPrice,
			Status:     sale.Status,
			ClientID:   sale.ClientID,
			CashierID:  sale.CashierID,
			FinishedAt: sale.FinishedAt,
			CreatedAt:  sale.CreatedAt,
		}
		return nil
	})

	if err != nil {
		return nil, err
	}
	return response, nil
}

// calculateProductConsumerPrice determines the highest active promotion discount and adds category-based taxes.
func (s *saleServiceImpl) calculateProductConsumerPrice(ctx context.Context, tx *gorm.DB, product *entities.Product) (float64, error) {
	// 1. Query all overlapping date-bounded promotional campaigns for product
	promos, err := s.productRepo.FindActivePromotionsByProductID(ctx, tx, product.ID, time.Now())
	if err != nil {
		return 0.0, exceptions.NewInternalError("Failed to find active promotions: " + err.Error())
	}

	// 2. Select maximum discount percentage
	var maxDiscount float64 = 0.0
	for _, promo := range promos {
		if promo.DiscountPercentage > maxDiscount {
			maxDiscount = promo.DiscountPercentage
		}
	}

	// 3. Apply maximum discount to product base price
	discountedBase := product.BasePrice * (1.0 - (maxDiscount / 100.0))

	// 4. Calculate final consumer price by adding tax percentage to discounted base price
	finalPrice := discountedBase * (1.0 + (product.TaxPercentage / 100.0))

	// 5. Round final value to 2 decimal places using HALF_UP
	return RoundHalfUp(finalPrice), nil
}

// assembleSaleDetailResponse maps internal entities to complete structured SaleDetailResponse DTO.
func (s *saleServiceImpl) assembleSaleDetailResponse(ctx context.Context, sale *entities.Sale, details []entities.SaleDetail) (*dto.SaleDetailResponse, error) {
	lineItems := make([]dto.LineItemResponse, len(details))
	for i, item := range details {
		prodName := item.Product.Name
		if prodName == "" {
			prod, err := s.productRepo.FindByID(ctx, item.ProductID)
			if err != nil {
				return nil, exceptions.NewInternalError("Failed to fetch product for details: " + err.Error())
			}
			if prod != nil {
				prodName = prod.Name
			}
		}
		lineItems[i] = dto.LineItemResponse{
			ItemID:    item.ID,
			ProductID: item.ProductID,
			Name:      prodName,
			UnitPrice: item.UnitPrice,
			Quantity:  item.Quantity,
			SubTotal:  item.SubTotal,
		}
	}

	return &dto.SaleDetailResponse{
		Sale: dto.SaleResponse{
			ID:         sale.ID,
			TotalPrice: sale.TotalPrice,
			Status:     sale.Status,
			ClientID:   sale.ClientID,
			CashierID:  sale.CashierID,
			FinishedAt: sale.FinishedAt,
			CreatedAt:  sale.CreatedAt,
		},
		LineItems: lineItems,
	}, nil
}

// GetSaleDetailByID retrieves details of a single line item.
func (s *saleServiceImpl) GetSaleDetailByID(ctx context.Context, id uint64) (*dto.LineItemResponse, error) {
	detail, err := s.saleRepo.FindDetailByID(ctx, id)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, exceptions.NewNotFoundError("Sale detail not found")
		}
		return nil, exceptions.NewInternalError("Database error fetching sale detail: " + err.Error())
	}
	if detail == nil {
		return nil, exceptions.NewNotFoundError("Sale detail not found")
	}

	return &dto.LineItemResponse{
		ItemID:    detail.ID,
		ProductID: detail.ProductID,
		Name:      detail.Product.Name,
		UnitPrice: detail.UnitPrice,
		Quantity:  detail.Quantity,
		SubTotal:  detail.SubTotal,
	}, nil
}