// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package config

import (
	"supermarket-backend/controllers"
	"supermarket-backend/repositories"
	"supermarket-backend/services"
)

// Injectors from wire.go:

// InitializeApp is the main Google Wire injector function.
// It assembles the entire component graph starting from the environment variables.
func InitializeApp() (*App, error) {
	cfg, err := Load()
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(cfg, logger)
	if err != nil {
		return nil, err
	}
	cache, err := NewCache(cfg, logger)
	if err != nil {
		return nil, err
	}

	userRepo := repositories.NewUserRepository(db)
	categoryRepo := repositories.NewCategoryRepository(db)
	clientRepo := repositories.NewClientRepository(db)
	productRepo := repositories.NewProductRepository(db)
	promotionRepo := repositories.NewPromotionRepository(db)
	saleRepo := repositories.NewSaleRepository(db)

	blacklist := NewRistrettoTokenBlacklist(cache)

	userService := services.NewUserService(userRepo, db, cfg, blacklist)
	categoryService := services.NewCategoryService(categoryRepo, productRepo, db)
	clientService := services.NewClientService(clientRepo, db)
	productService := services.NewProductService(productRepo, categoryRepo, db)
	promotionService := services.NewPromotionService(promotionRepo, productRepo, db)
	saleService := services.NewSaleService(saleRepo, productRepo, db)

	userCtrl := controllers.NewUserController(userService)
	catCtrl := controllers.NewCategoryController(categoryService)
	clientCtrl := controllers.NewClientController(clientService)
	prodCtrl := controllers.NewProductController(productService)
	promoCtrl := controllers.NewPromotionController(promotionService)
	saleCtrl := controllers.NewSaleController(saleService)

	app := NewApp(cfg, logger, db, cache, userCtrl, catCtrl, clientCtrl, prodCtrl, promoCtrl, saleCtrl)
	return app, nil
}
