// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-008 (AuthMiddleware)
// Service: SupermarketService
// Target Concern: middleware

package middleware

import (
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"supermarket-backend/dtos"
)

// TokenBlacklist defines the interface required to verify if a given JWT has been revoked/logout.
// This decouples the middleware from Ristretto/DB concrete implementations.
type TokenBlacklist interface {
	IsBlacklisted(token string) bool
}

// AuthMiddleware coordinates JWT verification, role-based checks, and resource ownership validation.
type AuthMiddleware struct {
	jwtSecret string
	blacklist TokenBlacklist
}

// NewAuthMiddleware constructs a new instance of AuthMiddleware with the given secret and blacklist checker.
func NewAuthMiddleware(jwtSecret string, blacklist TokenBlacklist) *AuthMiddleware {
	return &AuthMiddleware{
		jwtSecret: jwtSecret,
		blacklist: blacklist,
	}
}

// Authenticate returns a Gin handler that extracts and validates the JWT from the Authorization header.
// It injects 'operatorID' (uint64), 'role' (string), and 'username' (string) into the Gin context.
func (m *AuthMiddleware) Authenticate() gin.HandlerFunc {
	return func(c *gin.Context) {
		authHeader := c.GetHeader("Authorization")
		if authHeader == "" {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Authorization header is missing",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		parts := strings.SplitN(authHeader, " ", 2)
		if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Invalid Authorization header format. Expected 'Bearer <token>'",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		tokenStr := parts[1]

		// FR-032: Check active state against the Ristretto/database token blacklist
		if m.blacklist != nil && m.blacklist.IsBlacklisted(tokenStr) {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Token has been revoked",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		token, err := jwt.Parse(tokenStr, func(t *jwt.Token) (interface{}, error) {
			// Validate signing method
			if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
				return nil, jwt.ErrSignatureInvalid
			}
			return []byte(m.jwtSecret), nil
		})

		if err != nil || !token.Valid {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Token is invalid or expired",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		claims, ok := token.Claims.(jwt.MapClaims)
		if !ok {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Failed to decode token claims",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		// Extract 'sub' claim as OperatorID (uint64)
		var operatorID uint64
		if subClaim, exists := claims["sub"]; exists {
			switch v := subClaim.(type) {
			case float64:
				operatorID = uint64(v)
			case int64:
				operatorID = uint64(v)
			case uint64:
				operatorID = v
			case string:
				parsed, parseErr := strconv.ParseUint(v, 10, 64)
				if parseErr == nil {
					operatorID = parsed
				}
			}
		}

		if operatorID == 0 {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: Token missing subject claim",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		// Extract 'role' claim (string)
		var role string
		if roleClaim, exists := claims["role"]; exists {
			if rStr, ok := roleClaim.(string); ok {
				role = rStr
			}
		}

		// Extract 'user' claim (string)
		var username string
		if userClaim, exists := claims["user"]; exists {
			if uStr, ok := userClaim.(string); ok {
				username = uStr
			}
		}

		// Inject operator claims into Gin Context for downstream handlers (controllers)
		c.Set("operatorID", operatorID)
		c.Set("role", role)
		c.Set("username", username)

		c.Next()
	}
}

// AuthorizeRoles restricts endpoint access to specified roles only.
// Must be chained after Authenticate().
func (m *AuthMiddleware) AuthorizeRoles(allowedRoles ...string) gin.HandlerFunc {
	return func(c *gin.Context) {
		roleVal, exists := c.Get("role")
		if !exists {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: operator session not found",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		userRole, ok := roleVal.(string)
		if !ok {
			c.AbortWithStatusJSON(http.StatusForbidden, dto.ErrorResponse{
				ErrorCode: "ACCESS_DENIED",
				Message:   "Access denied: invalid session role claim",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		// Check if the role is allowed
		roleAllowed := false
		for _, r := range allowedRoles {
			if strings.EqualFold(r, userRole) {
				roleAllowed = true
				break
			}
		}

		if !roleAllowed {
			c.AbortWithStatusJSON(http.StatusForbidden, dto.ErrorResponse{
				ErrorCode: "ACCESS_DENIED",
				Message:   "Access denied: insufficient permissions to perform action",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		c.Next()
	}
}

// ValidateOwnerOrAdmin validates resource ownership vs authenticated claims (FR-030).
// Specifically, it checks if the authenticated operator ID matches the target path parameter ':id',
// unless the operator's role is 'ADMIN' (coarse authority bypasses ownership).
// Must be chained after Authenticate().
func (m *AuthMiddleware) ValidateOwnerOrAdmin() gin.HandlerFunc {
	return func(c *gin.Context) {
		roleVal, roleExists := c.Get("role")
		idVal, idExists := c.Get("operatorID")

		if !roleExists || !idExists {
			c.AbortWithStatusJSON(http.StatusUnauthorized, dto.ErrorResponse{
				ErrorCode: "UNAUTHORIZED",
				Message:   "Authentication required: operator session details missing",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		userRole, _ := roleVal.(string)
		operatorID, _ := idVal.(uint64)

		// ADMIN role bypasses ownership validation entirely
		if strings.EqualFold(userRole, "ADMIN") {
			c.Next()
			return
		}

		// Retrieve target path parameter :id
		pathIDStr := c.Param("id")
		if pathIDStr == "" {
			c.AbortWithStatusJSON(http.StatusBadRequest, dto.ErrorResponse{
				ErrorCode: "VALIDATION_FAILED",
				Message:   "Validation failed: missing path parameter 'id'",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		pathID, err := strconv.ParseUint(pathIDStr, 10, 64)
		if err != nil {
			c.AbortWithStatusJSON(http.StatusBadRequest, dto.ErrorResponse{
				ErrorCode: "VALIDATION_FAILED",
				Message:   "Validation failed: parameter 'id' must be a valid positive integer",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		// Compare path parameter user ID against authenticated operator's user ID
		if pathID != operatorID {
			c.AbortWithStatusJSON(http.StatusForbidden, dto.ErrorResponse{
				ErrorCode: "ACCESS_DENIED",
				Message:   "Access denied: non-admin operators are prohibited from reading or modifying another user's profile",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		c.Next()
	}
}