// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-008 (AuthMiddleware & Context Logging)
// Service: SupermarketService
// Target Concern: middleware

package middleware

import (
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
)

const (
	// CorrelationIDHeader is the standard HTTP response/request header for tracing.
	CorrelationIDHeader = "X-Correlation-ID"

	// CorrelationIDContextKey is the Gin context key used to store the trace/correlation ID.
	CorrelationIDContextKey = "transactionId"

	// LoggerContextKey is the Gin context key used to store the request-scoped Zap logger.
	LoggerContextKey = "logger"
)

// GenerateCorrelationID generates a secure random 32-character hex string (16 bytes)
// to serve as a globally unique trace/correlation ID without external library dependencies.
func GenerateCorrelationID() string {
	bytes := make([]byte, 16)
	if _, err := rand.Read(bytes); err != nil {
		// Secure fallback using timestamp in nanoseconds
		return "tr-" + hex.EncodeToString([]byte(time.Now().Format("20060102150405.000000")))
	}
	return hex.EncodeToString(bytes)
}

// LoggerMiddleware constructs a Gin logging interceptor using Uber Zap.
// It injects a request-scoped correlation ID and a pre-configured logger into the context.
func LoggerMiddleware(baseLogger *zap.Logger) gin.HandlerFunc {
	return func(c *gin.Context) {
		// 1. Resolve or generate correlation ID (transactionId)
		correlationID := c.GetHeader(CorrelationIDHeader)
		if correlationID == "" {
			correlationID = GenerateCorrelationID()
		}

		// Set response header to return the correlation ID for end-to-end tracing
		c.Header(CorrelationIDHeader, correlationID)

		// 2. Inject correlation ID into Gin context
		c.Set(CorrelationIDContextKey, correlationID)

		// 3. Create a request-scoped logger pre-injected with the correlation ID (transactionId)
		reqLogger := baseLogger.With(
			zap.String("transactionId", correlationID),
			zap.String("method", c.Request.Method),
			zap.String("path", c.Request.URL.Path),
		)
		c.Set(LoggerContextKey, reqLogger)

		// 4. Capture starting execution timestamp
		startTime := time.Now()

		// 5. Forward to downstream middleware and route handlers
		c.Next()

		// 6. Calculate execution latency in milliseconds
		executionTimeMs := float64(time.Since(startTime).Nanoseconds()) / 1e6

		// 7. Extract downstream values that might have been injected during handling (e.g., operatorID)
		var operatorID uint64
		if opVal, exists := c.Get("operatorID"); exists {
			if opID, ok := opVal.(uint64); ok {
				operatorID = opID
			}
		}

		statusCode := c.Writer.Status()
		responseSize := c.Writer.Size()
		clientIP := c.ClientIP()

		// Log fields following the SAD's Uber Zap structured JSON conventions
		logFields := []zap.Field{
			zap.String("transactionId", correlationID),
			zap.Float64("executionTimeMs", executionTimeMs),
			zap.Int("status", statusCode),
			zap.Int("response_bytes", responseSize),
			zap.String("client_ip", clientIP),
			zap.String("user_agent", c.Request.UserAgent()),
		}

		// Only log operatorId if a valid authenticated session was resolved
		if operatorID > 0 {
			logFields = append(logFields, zap.Uint64("operatorId", operatorID))
		}

		// Log using status-specific log levels
		msg := "HTTP request processed"
		if statusCode >= http.StatusInternalServerError {
			reqLogger.Error(msg, logFields...)
		} else if statusCode >= http.StatusBadRequest {
			reqLogger.Warn(msg, logFields...)
		} else {
			reqLogger.Info(msg, logFields...)
		}
	}
}

// GetLogger retrieves the request-scoped logger injected by LoggerMiddleware.
// If not found, it returns a safe, no-operation logger to prevent nil-pointer exceptions.
func GetLogger(c *gin.Context) *zap.Logger {
	if val, exists := c.Get(LoggerContextKey); exists {
		if logger, ok := val.(*zap.Logger); ok {
			return logger
		}
	}
	// Fallback to standard structured logger configuration if request-specific one is not found
	return zap.NewNop()
}

// GetCorrelationID extracts the request trace/transaction identifier from the context.
func GetCorrelationID(c *gin.Context) string {
	if val, exists := c.Get(CorrelationIDContextKey); exists {
		if id, ok := val.(string); ok {
			return id
		}
	}
	return ""
}