// Code generated by FEP sub-agent. DO NOT EDIT.
// Contract ID: CTR-008 (Rate Limiting Middleware)
// Service: SupermarketService
// Target Concern: middleware

package middleware

import (
	"net/http"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"supermarket-backend/dtos"
)

// tokenBucket represents a rate limiting token bucket for a single IP address.
type tokenBucket struct {
	tokens       float64
	lastRefilled time.Time
}

// IPRateLimiter provides thread-safe IP-based rate limiting using a token-bucket algorithm.
// It is completely self-contained with no external dependencies.
type IPRateLimiter struct {
	mu    sync.RWMutex
	ips   map[string]*tokenBucket
	rate  float64 // rate at which tokens are added per second
	burst float64 // maximum tokens the bucket can hold
}

// NewIPRateLimiter instantiates a rate limiter configured with target rate and burst capacity.
// - rate: number of requests permitted per second (per IP)
// - burst: maximum allowance of concurrent burst requests
func NewIPRateLimiter(rate float64, burst float64) *IPRateLimiter {
	return &IPRateLimiter{
		ips:   make(map[string]*tokenBucket),
		rate:  rate,
		burst: burst,
	}
}

// Limit returns a Gin middleware handler enforcing the configured rate limits per client IP.
func (l *IPRateLimiter) Limit() gin.HandlerFunc {
	return func(c *gin.Context) {
		ip := c.ClientIP()

		if !l.allow(ip) {
			c.AbortWithStatusJSON(http.StatusTooManyRequests, dto.ErrorResponse{
				ErrorCode: "TOO_MANY_REQUESTS",
				Message:   "Rate limit exceeded: too many requests. Please try again later.",
				Timestamp: time.Now().UTC(),
			})
			return
		}

		c.Next()
	}
}

// allow checks if a token can be drawn from the bucket associated with the IP.
// It also cleans up expired buckets to prevent memory leakage when client IPs scale.
func (l *IPRateLimiter) allow(ip string) bool {
	l.mu.Lock()
	defer l.mu.Unlock()

	now := time.Now()

	// 1. Memory Safety Sweep: If unique client map is exceptionally large,
	// prune stale buckets inactive for more than 1 hour.
	if len(l.ips) > 5000 {
		for clientIP, bucket := range l.ips {
			if now.Sub(bucket.lastRefilled) > 1*time.Hour {
				delete(l.ips, clientIP)
			}
		}
	}

	bucket, exists := l.ips[ip]
	if !exists {
		l.ips[ip] = &tokenBucket{
			tokens:       l.burst - 1.0, // Draw first token immediately
			lastRefilled: now,
		}
		return true
	}

	// 2. Refill tokens based on elapsed duration
	elapsed := now.Sub(bucket.lastRefilled).Seconds()
	bucket.tokens += elapsed * l.rate
	if bucket.tokens > l.burst {
		bucket.tokens = l.burst
	}
	bucket.lastRefilled = now

	// 3. Draw token if available
	if bucket.tokens >= 1.0 {
		bucket.tokens -= 1.0
		return true
	}

	return false
}
